"""Persisted activity status labels and shared status groups."""

NOT_STARTED = "未开始"
ONGOING = "进行中"
ENDED = "已结束"
CANCELLED = "已取消"
FLOW_CANCELLED = "已流局"

CANCELLED_ACTIVITY_STATUSES = (CANCELLED, FLOW_CANCELLED)
TERMINAL_ACTIVITY_STATUSES = frozenset({ENDED, *CANCELLED_ACTIVITY_STATUSES})
ACTIVE_ACTIVITY_STATUSES = frozenset({NOT_STARTED, ONGOING})
RETROACTIVE_CHECKIN_STATUSES = frozenset({ONGOING, ENDED})
