const api=require('../../services/boardgames'),upload=require('../../services/boardgameImportUpload').upload;
const segments=require('../../services/boardgameImportSegments');
const STATES={queued:'排队中',fetching:'查询来源中',parsing:'解析中',retry_wait:'等待来源重试',ready:'可核对',applying:'保存中',applied:'已处理',partial:'部分待处理',failed:'处理失败',needs_mapping:'待匹配',needs_review:'待核对',skipped:'已跳过',linked:'已关联'};
const KINDS={bgg_thing:'BGG 游戏资料',bgg_collection:'BGG 收藏',bgg_plays:'BGG 对局',bgstats_file:'BG Stats 文件',bgstats_game:'游戏资料',bgstats_copy:'实物记录',bgstats_play:'对局记录',bgg_play:'对局记录'};
const ISSUES={source_copy_identity_unstable:'这盒桌游缺少稳定来源编号，再次导入需人工核对，避免重复录入',team_result_review_required:'团队分组和队伍成绩需要核对',source_winner_rank_conflict:'赢家与名次不一致',source_winner_score_or_tiebreak_review:'赢家与分数或同分决胜需要核对',source_copy_not_currently_owned:'来源未标记为当前拥有，不能直接新增为在库实物',source_purchase_price_requires_review:'来源价格或币种格式需要核对',source_expression_requires_review:'原始分数算式暂不能确定',unknown_play_date:'没有明确游玩日期',quantity_split_review_required:'这条来源包含多局，需分别确认日期和成绩',source_sheet_requires_review:'计分结构尚未识别，原件保留',ambiguous_source_time:'来源时间有夏令时歧义',source_timezone_date_adjusted:'按北京时间转换后，日期发生变化'};
const FIELDS={duration_minutes:'时长',round_count:'轮数',note:'备注',played_on:'日期',started_at:'开始时间',competition_mode:'比赛方式',players:'玩家与成绩',expansions:'使用扩展',scoresheet:'计分表',source_result_valid:'结果是否一致',variant_key:'变体',score_direction:'记分方向'};
function title(item){const n=item.normalized||{};return n.game_name||(n.projection||{}).name||KINDS[item.source_kind]||'来源条目';}
function short(value){if(value===null||value===undefined)return '未填写';if(Array.isArray(value))return value.map(v=>v&&typeof v==='object'?(v.score!==undefined?`${v.name||'参与者'}：${v.score??'未填'}`:v.name||v.game_name||'一项'):String(v)).join('、');if(typeof value==='object')return '已保留结构，请对照计分表';return String(value).slice(0,500);}
Page({data:{id:null,jobs:[],job:null,items:[],loading:false,saving:false,error:'',notice:'',capabilities:[],nextCursor:null,itemCursor:null,
 segmentKey:null,segments:[],createOpen:false,source:'bgstats',file:null,username:'',bggKind:'bgg_collection',bggKinds:[{value:'bgg_collection',label:'收藏 / 拥有的游戏'},{value:'bgg_plays',label:'对局历史'}],bggKindIndex:0,datasets:[],datasetIndex:0,timezone:'Asia/Shanghai',
 reviewOpen:false,review:null,selected:null,game:null,inventoryOverride:false,inventoryForm:{},inventoryStatuses:[{value:'unverified',label:'待核实'},{value:'available',label:'可用'},{value:'borrowed',label:'借出'},{value:'unavailable',label:'暂不可用'},{value:'retired',label:'已退役'}],inventoryStatusIndex:0,locationChoice:null,decisionPlayers:[],acknowledged:false,reason:'',replaceSheet:false,action:'create_play',targetPlay:null,reportOpen:false,report:null,
 pickerOpen:false,pickerKind:'game',pickerTitle:'选择游戏',pickerQuery:'',pickerItems:[],pickerCursor:null,personSlot:null,
 publishOpen:false,publishPlay:null,publishPublic:false,publishPeople:false,publishReason:'',mappings:[],mappingsOpen:false,mappingCursor:null,mappingHistory:[],historyOpen:false,isAdmin:false,ownerId:null,ownerName:'我自己的数据'},
 onLoad(options){this.setData({id:options.id||null,isAdmin:wx.getStorageSync('userRole')==='admin'});},onShow(){this.load();if(this.data.segmentKey){try{this.setData({segments:segments.summary(segments.read(this.data.segmentKey))});}catch(e){this.setData({error:api.message(e)});}}},
 async load(){this.setData({loading:true,error:''});try{const c=await api.get('/boardgame-imports/capabilities');this.setData({capabilities:c.items});if(this.data.id){const job=await api.get(`/boardgame-imports/${this.data.id}`);this.setData({job:{...job,stateLabel:STATES[job.state],kindLabel:KINDS[job.kind]},jobBusy:['queued','fetching','parsing','applying','retry_wait'].includes(job.state)});await this.loadItems();}else{const r=await api.get('/boardgame-imports',{limit:30});this.setData({jobs:r.items.map(j=>({...j,stateLabel:STATES[j.state],kindLabel:KINDS[j.kind]})),nextCursor:r.next_cursor});}}catch(e){this.setData({error:api.message(e)});}finally{this.setData({loading:false});}},
 async loadItems(more=false){const r=await api.get(`/boardgame-imports/${this.data.id}/items`,{limit:20,cursor:more?this.data.itemCursor:null});const rows=r.items.map(i=>({...i,title:title(i),kindLabel:KINDS[i.source_kind],stateLabel:STATES[i.state]}));this.setData({items:more?[...this.data.items,...rows]:rows,itemCursor:r.next_cursor});},
 async more(){try{if(this.data.id)await this.loadItems(true);else{const r=await api.get('/boardgame-imports',{limit:30,cursor:this.data.nextCursor});this.setData({jobs:[...this.data.jobs,...r.items.map(j=>({...j,stateLabel:STATES[j.state],kindLabel:KINDS[j.kind]}))],nextCursor:r.next_cursor});}}catch(e){this.setData({error:api.message(e)});}},
 openJob(e){wx.navigateTo({url:`/pages/boardgame_imports/boardgame_imports?id=${e.currentTarget.dataset.id}`});},
 async openCreate(){this._createKey=api.uuid();this.setData({createOpen:true,error:''});try{const r=await api.get('/boardgame-imports/datasets');this.setData({datasets:[{id:null,label:'首次导入，建立新数据集'},...r.items.map((d,i)=>({...d,label:`已有数据集 ${i+1} · 继续同步映射`}))]});}catch(e){this.setData({error:api.message(e)});}},closeCreate(){if(!this.data.saving)this.setData({createOpen:false});},source(e){this._createKey=api.uuid();this.setData({source:e.currentTarget.dataset.value});},field(e){this._createKey=api.uuid();this.setData({[e.currentTarget.dataset.key]:e.detail.value});},bggKind(e){const i=Number(e.detail.value);this.setData({bggKindIndex:i,bggKind:this.data.bggKinds[i].value});this._createKey=api.uuid();},dataset(e){this.setData({datasetIndex:Number(e.detail.value)});this._createKey=api.uuid();},
 chooseFile(){wx.chooseMessageFile({count:1,type:'file',extension:['json','bgsplay'],success:r=>{const f=r.tempFiles[0];if(f.size>20*1024*1024)return this.setData({error:'文件不能超过 20 MiB'});this._createKey=api.uuid();this.setData({file:{path:f.path,name:f.name,size:f.size}});},fail:e=>{if(!String(e.errMsg).includes('cancel'))this.setData({error:'未能选择文件，请重试'});}});},
 async create(){if(this.data.saving)return;this.setData({saving:true,error:''});try{let r;if(this.data.source==='bgstats'){if(!this.data.file)throw new Error('请先选择 BG Stats 导出文件');const dataset=this.data.datasets[this.data.datasetIndex];r=await upload(this.data.file.path,{...(dataset&&dataset.id?{source_dataset:dataset.id}:{}),source_timezone:this.data.timezone,...(this.data.ownerId?{owner_user_id:String(this.data.ownerId)}:{})},this._createKey);}else r=await api.send('/boardgame-imports','POST',{kind:this.data.bggKind,username:this.data.username,...(this.data.ownerId?{owner_user_id:this.data.ownerId}:{})},this._createKey);this.setData({createOpen:false,file:null});wx.navigateTo({url:`/pages/boardgame_imports/boardgame_imports?id=${r.id}`});}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 async review(e){const item=this.data.items.find(i=>i.id===Number(e.currentTarget.dataset.id));if(!item)return;this.setData({selected:item,review:null,segments:[],segmentKey:null,reviewOpen:true,acknowledged:false,reason:'',replaceSheet:false,error:''});try{const r=await api.get(`/boardgame-imports/${this.data.id}/items/${item.id}/preview`);const game=r.mapped_game_id?await api.get(`/boardgames/${r.mapped_game_id}`):null;
  const persons=r.player_slots.map(p=>({...p,choice:p.mapping&&p.mapping.target?{person_id:p.mapping.target.id,label:p.mapping.target.name}:null}));
  this.setData({review:{...r,issueLabels:r.issues.map(k=>ISSUES[k]||'存在未识别或需人工核对的来源字段'),same_source:r.same_source.map(s=>({...s,differences:(s.differences||[]).map(d=>({...d,label:FIELDS[d.field]||'来源其他字段',beforeText:short(d.before),afterText:short(d.after)}))}))},game,decisionPlayers:persons,locationChoice:r.location_mapping&&r.location_mapping.target?{location_id:r.location_mapping.target.id,label:r.location_mapping.target.name}:null,
   inventoryOverride:false,inventoryForm:{...(r.normalized.inventory||{}),status:'unverified',quantity:r.normalized.quantity||1},inventoryStatusIndex:0,canDecide:!['applied','linked','skipped'].includes(item.state),
   action:item.source_kind.endsWith('game')||item.source_kind==='thing'?'create_game':item.source_kind.endsWith('copy')||item.source_kind==='bgg_collection'?'create_inventory':'create_play',targetPlay:null});if(game&&this.data.action==='create_play'&&Number(r.normalized.quantity)>1){const local=segments.prepare(this.data.id,item,r,game);this.setData({segmentKey:local.key,segments:segments.summary(local.bundle)});}}catch(e){this.setData({error:api.message(e)});}},
 async editSegment(e){try{if(!this.data.game)throw new Error('请先选择对应的本地游戏');const local=segments.prepare(this.data.id,this.data.selected,this.data.review,this.data.game);this.setData({segmentKey:local.key,segments:segments.summary(local.bundle)});wx.navigateTo({url:'/pages/boardgame_play/boardgame_play'+api.query({segment_key:local.key,segment_index:Number(e.currentTarget.dataset.index)||0})});}catch(e){this.setData({error:api.message(e)});}},
 inventoryField(e){this.setData({[`inventoryForm.${e.currentTarget.dataset.key}`]:e.detail.value});},inventoryStatus(e){const i=Number(e.detail.value);this.setData({inventoryStatusIndex:i,'inventoryForm.status':this.data.inventoryStatuses[i].value});},
 closeReview(){if(!this.data.saving)this.setData({reviewOpen:false});},ack(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},
 async openPicker(e){const kind=e.currentTarget.dataset.kind;this.setData({pickerOpen:true,pickerKind:kind,pickerTitle:kind==='game'?'匹配本地游戏':kind==='owner'?'数据归属账号':kind==='location'?'匹配游玩地点':'匹配小程序成员',personSlot:Number(e.currentTarget.dataset.slot),pickerQuery:'',pickerItems:[],pickerCursor:null});await this.searchPicker();},closePicker(){this.setData({pickerOpen:false});},pickerInput(e){this.setData({pickerQuery:e.detail.value});},
 async searchPicker(e){const more=e&&e.currentTarget&&e.currentTarget.dataset.more;try{const kind=this.data.pickerKind,path=kind==='game'?'/boardgames':kind==='owner'?'/boardgame-members':kind==='location'?'/boardgame-locations':'/boardgame-people';const r=await api.get(path,{q:this.data.pickerQuery,limit:50,cursor:more?this.data.pickerCursor:null,...(kind==='person'?{registered_only:true}:{})});const list=r.items.map(x=>({...x,label:x.name||x.display_name||x.nickname}));this.setData({pickerItems:more?[...this.data.pickerItems,...list]:list,pickerCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}},
 choose(e){const obj=this.data.pickerItems.find(i=>i.id===Number(e.currentTarget.dataset.id));if(!obj)return;if(this.data.pickerKind==='game')this.setData({game:obj,segments:[],segmentKey:null});else if(this.data.pickerKind==='owner')this.setData({ownerId:obj.id,ownerName:obj.label});else if(this.data.pickerKind==='location')this.setData({locationChoice:{location_id:obj.id,label:obj.label}});else this.setData({decisionPlayers:this.data.decisionPlayers.map(p=>p.source_slot===this.data.personSlot?{...p,choice:{person_id:obj.id,label:obj.label}}:p)});this._createKey=api.uuid();this.setData({pickerOpen:false});},
 keepLocation(){const name=this.data.review.normalized.location_name;if(name)this.setData({locationChoice:{create_location:{name},label:'单独保留来源地点：'+name}});},
 keepUnmatched(e){const slot=Number(e.currentTarget.dataset.slot);this.setData({decisionPlayers:this.data.decisionPlayers.map(p=>p.source_slot===slot?{...p,choice:{create_person:{display_name:p.name},label:'保留为待匹配玩家'}}:p)});},
 action(e){const action=e.currentTarget.dataset.action,id=Number(e.currentTarget.dataset.id),target=(this.data.review.candidates||[]).find(p=>p.id===id)||(this.data.review.same_source||[]).find(p=>p.play_id===id);this.setData({action,targetPlay:target?{id:target.id||target.play_id,revision:target.revision}:null});},
 async saveDecision(e){if(this.data.saving)return;this.setData({saving:true,error:''});try{const action=e.currentTarget.dataset.action||this.data.action,item=this.data.selected,review=this.data.review;
  if(action!=='skip'&&review.issues.length&&!this.data.acknowledged)throw new Error('请逐项核对来源提示并勾选确认');
  const body={action,reason:this.data.reason||null,acknowledged_issues:this.data.acknowledged?review.issues:[],replace_scoresheet:this.data.replaceSheet};
  if(this.data.game)body.target_game_id=this.data.game.id;
  if(action==='create_inventory'&&this.data.inventoryOverride){if(!this.data.game)throw new Error('请先匹配本地游戏');const f=this.data.inventoryForm;body.inventory={...f,game_id:this.data.game.id,owner_user_id:this.data.job.params.owner_user_id,available_for_activity:false,quantity:Number(f.quantity),purchase_price:f.purchase_price===''||f.purchase_price===undefined?null:f.purchase_price,purchase_currency:f.purchase_price===''||f.purchase_price===undefined||f.purchase_price===null?null:(f.purchase_currency||'CNY'),purchased_on:f.purchased_on||null};}
  if(action==='create_game'&&this.data.game){body.game={name:this.data.game.name};}
  if(['create_play','update_play'].includes(action)){const loc=this.data.locationChoice;if(loc){if(loc.location_id)body.location_id=loc.location_id;else if(loc.create_location)body.create_location=loc.create_location;}body.players=this.data.decisionPlayers.map(p=>{if(p.is_anonymous)return {source_player_ref:p.source_player_ref,source_slot:p.source_slot,source_score_uuid:p.source_score_uuid,is_anonymous:true,guest_label:p.name};if(!p.choice)throw new Error('请逐一匹配玩家，或明确保留为待匹配玩家');return {source_player_ref:p.source_player_ref,source_slot:p.source_slot,source_score_uuid:p.source_score_uuid,...(p.choice.person_id?{person_id:p.choice.person_id}:{create_person:p.choice.create_person})};});}
  if(action==='create_play'&&Number(review.normalized.quantity)>1){if(!this.data.game)throw new Error('请先匹配本地游戏');const local=segments.prepare(this.data.id,item,review,this.data.game);if(!local.bundle.entries.every(e=>e.confirmed&&e.payload))throw new Error('请先逐局核对日期、玩家和成绩');body.segment_count=local.bundle.entries.length;body.segments=local.bundle.entries.map(e=>e.payload);body.segment_player_slots=local.bundle.entries.map(e=>e.slots);}
  if(['link_play','update_play'].includes(action)){if(!this.data.targetPlay)throw new Error('请选择需要关联或更新的对局');body.target_play_id=this.data.targetPlay.id;body.target_play_revision=this.data.targetPlay.revision;}
  const reviewed=await api.send(`/boardgame-imports/${this.data.id}/items/${item.id}`,'PATCH',{expected_revision:item.revision,decision:body});
  const latest=await api.get(`/boardgame-imports/${this.data.id}`);await api.send(`/boardgame-imports/${this.data.id}/apply`,'POST',{expected_revision:latest.revision,selection:[{id:item.id,expected_revision:reviewed.revision}]});this.setData({reviewOpen:false,notice:'已提交处理，完成后刷新查看。历史会继续保持私有。'});await this.load();
 }catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 editHeld(e){wx.navigateTo({url:`/pages/boardgame_play/boardgame_play?id=${e.currentTarget.dataset.id}&job_id=${this.data.id}&item_id=${this.data.selected.id}`});},
 async openReport(){try{const r=await api.get(`/boardgame-imports/${this.data.id}/report`);this.setData({report:{...r,counts:r.counts.map(c=>({...c,label:`${KINDS[c.kind]||'来源'} · ${STATES[c.state]||c.state}`})),outcomes:Object.entries(r.application_outcomes||{}).filter(([,v])=>v.items).map(([key,v])=>({...v,label:({created:'新增',reused:'复用',linked:'关联',updated:'更新',skipped:'跳过',legacy_unknown:'早期处理'})[key]})),publication:Object.entries(r.publication_counts||{}).map(([key,count])=>({label:key==='held'?'暂存历史':'已公开',count}))},reportOpen:true});}catch(e){this.setData({error:api.message(e)});}},closeReport(){this.setData({reportOpen:false});},
 async retry(){if(this.data.saving)return;this.setData({saving:true,error:''});try{const failed=this.data.items.filter(i=>i.state==='failed'&&i.decision).map(i=>i.id);await api.send(`/boardgame-imports/${this.data.id}/retry`,'POST',{expected_revision:this.data.job.revision,item_ids:failed});await this.load();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 openPublish(e){const p=this.data.review.applied_plays.find(p=>p.id===Number(e.currentTarget.dataset.id));this._publishKey=api.uuid();this.setData({publishOpen:true,publishPlay:p,publishPublic:false,publishPeople:false,publishReason:''});},closePublish(){if(!this.data.saving)this.setData({publishOpen:false});},
 async publish(){if(this.data.saving)return;this.setData({saving:true,error:''});try{if(!this.data.publishPublic)throw new Error('请确认此局内容将在小程序内公开');const p=this.data.publishPlay,job=await api.get(`/boardgame-imports/${this.data.id}`);await api.send(`/boardgame-imports/${this.data.id}/publish`,'POST',{expected_revision:job.revision,reason:this.data.publishReason,acknowledge_public:true,acknowledge_unmatched_people:this.data.publishPeople,
  selection:[{item_id:this.data.selected.id,play_id:p.id,expected_revision:p.revision,review_token:p.review_token}]},this._publishKey);this.setData({publishOpen:false,reviewOpen:false,notice:'所选对局已公开，按自身统计口径计入统计'});await this.load();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 async openMappings(){this.setData({mappingsOpen:true,mappings:[],mappingCursor:null});await this.moreMappings();},closeMappings(){this.setData({mappingsOpen:false});},async moreMappings(){try{const r=await api.get(`/boardgame-imports/${this.data.id}/mappings`,{limit:50,cursor:this.data.mappingCursor});this.setData({mappings:[...this.data.mappings,...r.items],mappingCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}},
 async mappingHistory(e){try{const r=await api.get(`/boardgame-imports/${this.data.id}/mappings/${e.currentTarget.dataset.id}/history`);this.setData({historyOpen:true,mappingHistory:r.items});}catch(e){this.setData({error:api.message(e)});}},closeHistory(){this.setData({historyOpen:false});}
});
