const api=require('../../services/boardgames'),F=require('../../utils/boardgameFilters');
const METRICS=[['overview','概览'],['wanted','最想开'],['most-played','开的最多'],['trends','趋势'],['breakdowns','分布'],['locations','地点'],['partners','伙伴'],['expansions','扩展'],['players','玩家排名'],['detailed','详细结果'],['streaks','连胜'],['score-curve','得分曲线'],['variants','角色与变体'],['scoresheets','计分分项']].map(([value,label])=>({value,label}));
const MODES=[['individual','个人竞赛'],['team','团队竞赛'],['cooperative','合作'],['solo','单人']].map(([value,label])=>({value,label}));
const MENU_GROUPS=[{label:'游玩与偏好',values:['overview','wanted','most-played','trends','breakdowns','locations','expansions']},{label:'玩家与伙伴',values:['partners','players','detailed','streaks']},{label:'成绩与规则',values:['score-curve','variants','scoresheets']}].map(g=>({...g,items:METRICS.filter(m=>g.values.includes(m.value))}));
const NEED_GAME=new Set(['players','detailed','streaks','score-curve','variants','scoresheets']);
const LABELS={completed_play_count:'完成对局',game_count:'玩过游戏',played_day_count:'游玩天数',known_duration_minutes:'已记录分钟',duration_missing_count:'时长缺失局数',h_index:'H 指数',abandoned_count:'没开完',registered_player_count:'小程序玩家',player_appearances:'实际参局人次',new_to_player_game_count:'新玩游戏',play_count:'对局数',tiebreak_play_count:'手动决胜局数',first_player_missing_play_count:'先手未记录局数',new_player_flag_missing_samples:'新手标记缺失人次'};
function metrics(data,names=LABELS){return Object.keys(names).filter(k=>data[k]!==undefined).map(k=>({key:k,label:names[k],value:F.number(data[k])}));}
function rowView(row,metric,index){const result=row.result||{},name=row.game?row.game.name:row.person?row.person.display_name:row.location?row.location.name:
 row.row_label||row.variant_key&&`${row.variant_key} · ${row.role_label||'未填角色'}`||row.played_on||row.role_label||row.key===0&&'未记录地点'||row.key||'未分类';
 let value=row.play_count??row.completed_play_count??row.shared_play_count??row.nomination_count??0,detail='';
 if(metric==='wanted'){value=row.nomination_count;detail=`${row.activity_count} 场活动 · 我的提名 ${row.my_activity_count} 次`;}
 if(metric==='players'){detail=`有效样本 ${result.eligible_games??result.eligible_samples??0} · 胜率 ${F.percent(result.win_rate??result.success_rate)}`;}
 if(metric==='streaks'){value=row.longest_win_streak;detail=`当前连胜 ${row.current_win_streak}`;}
 if(metric==='score-curve'){value=row.score;detail=row.outcome==='win'?'获胜':row.outcome==='loss'?'未获胜':'结果待核对';}
 if(metric==='variants')detail=`胜率 ${F.percent(row.win_rate)} · 结果样本 ${row.result_samples}`;
 if(metric==='scoresheets'){value=row.average;detail=`均分 · ${row.numeric_samples} 个数值样本，${row.missing_samples} 项缺失`;
  row.resultRows=Object.entries(row.by_result||{}).map(([key,r])=>({key,label:{winner:'胜者',non_winner:'未获胜',unknown:'未知 / 排除'}[key],value:F.number(r.average),samples:r.numeric_samples,drilldown:r.drilldown}));}
 return {...row,cover:row.game&&row.game.cover_url||null,avatar:row.person&&row.person.user&&row.person.user.avatar_url||null,displayKey:String(row.key||row.person&&row.person.id||row.row_key||`${row.play_id}:${row.subject_id}`||index),label:String(name),value:F.number(value),numeric:Number(value)||0,caption:detail};}
Page({...require('../../utils/boardgameMedia'),data:{query:{},metricOpen:false,metricGroups:MENU_GROUPS,overviewTrend:[],overviewTop:[],overviewExtraError:'',periodLabel:'全部时间',gameCursor:null,sourcesCursor:null,metric:'overview',metricIndex:0,metrics:METRICS,modes:MODES,modeIndex:0,loading:false,error:'',cards:[],rows:[],filterOpen:false,groups:[],groupIndex:0,sheetGroups:[],sheetGroupIndex:0,nextCursor:null,gameOpen:false,games:[],gameSearch:'',gameName:'全部游戏',detailSections:[],resultGroups:[],distributionIndex:0,bucketIndex:0,
 distributions:['按星期','按人数','按环境'],buckets:['按月','按季度','按年','按活动'],sourcesOpen:false,sources:[]},
 onLoad(options){const q=F.load(options);this.setData({query:q});if(options.metric&&METRICS.some(m=>m.value===options.metric))this.setData({metric:options.metric,metricIndex:METRICS.findIndex(m=>m.value===options.metric)});},
 onShow(){this.load();},onReachBottom(){if(this.data.nextCursor&&!this.data.loading)this.load(true);},
 apiQuery(){const q={...F.clean(this.data.query)};if(NEED_GAME.has(this.data.metric)&&!q.mode)q.mode='individual';if(this.data.metric==='wanted'){const out={};['scope','period','year','month','quarter','from','to','activity_ids','game_id'].forEach(k=>{if(q[k]!==undefined)out[k]=q[k];});return out;}delete q.status;delete q.recorded_by;return q;},
 async load(more=false){more=more===true;const generation=this._generation=(this._generation||0)+1;const metric=this.data.metric,q=this.apiQuery();const periodLabel=q.period==='month'?`${q.year} 年 ${q.month} 月`:q.period==='quarter'?`${q.year} 年第 ${q.quarter} 季度`:q.period==='year'?`${q.year} 年`:q.period==='custom'?`${q.from} 至 ${q.to}`:'全部时间';this.setData({periodLabel,loading:true,error:'',showRules:NEED_GAME.has(metric),needsGame:NEED_GAME.has(metric)&&!q.game_id});
  try{if(NEED_GAME.has(metric)&&!q.game_id){this.setData({rows:[],cards:[],detailSections:[],resultGroups:[]});return;}
    if(q.game_id&&!more){const game=await api.get(`/boardgames/${q.game_id}`);if(generation!==this._generation)return;this.setData({gameName:game.name});}
    if(NEED_GAME.has(metric)&&!more){const g=await api.get(`/boardgame-stats/games/${q.game_id}/comparison-groups`,q);if(generation!==this._generation)return;this.setData({groups:[{label:'同一游戏全部规则',comparison_key:null},...g.items.map((r,i)=>({...r,label:`规则组 ${i+1} · ${r.rules.variant_key||'标准玩法'} · ${r.play_count} 局`}))],groupIndex:Math.max(0,g.items.findIndex(g=>g.comparison_key===q.comparison_key)+1),modeIndex:Math.max(0,MODES.findIndex(m=>m.value===q.mode))});}
    if(metric==='scoresheets'&&!more){const sg=await api.get(`/boardgame-stats/games/${q.game_id}/scoresheet-groups`,q);if(generation!==this._generation)return;this.setData({sheetGroups:sg.items.map((g,i)=>({...g,label:`计分结构 ${i+1} · ${g.play_count} 局`}))});if(!q.sheet_comparison_key&&sg.items.length){q.sheet_comparison_key=sg.items[0].sheet_comparison_key;this.setData({'query.sheet_comparison_key':q.sheet_comparison_key});}}
    if((metric==='score-curve'&&!q.comparison_key)||(metric==='scoresheets'&&!q.sheet_comparison_key)){this.setData({rows:[],cards:[],emptyReason:metric==='score-curve'?'选择相同规则组后比较分数':'这个范围还没有可比较的计分表'});return;}
    const path=NEED_GAME.has(metric)?`/boardgame-stats/games/${q.game_id}/${metric}`:`/boardgame-stats/${metric}`;
    const r=await api.get(path,{...q,limit:20,cursor:more?this.data.nextCursor:null});if(generation!==this._generation)return;
    let rows=(r.items||[]).map((row,i)=>rowView(row,metric,i));if(more)rows=[...this.data.rows,...rows];const max=Math.max(1,...rows.map(r=>Math.abs(r.numeric)));rows=rows.map(r=>({...r,bar:Math.max(0,Math.abs(r.numeric)/max*100)}));
    const sections=[];if(metric==='detailed'){[['result','全部人类参局'],['first_player','先手'],['not_first_player','非先手'],['new_player','第一次玩'],['experienced_player','玩过的玩家']].forEach(([k,label])=>{const v=r[k];sections.push({key:k,label,value:F.percent(v.win_rate),caption:`${v.wins} 次获胜 / ${v.eligible_samples} 个已知样本，未知或排除 ${v.unknown_or_excluded_samples}`,drilldown:r.drilldowns[k]});});if(r.scores)sections.push(...metrics(r.scores,{average:'平均得分',winning_average:'胜者均分',best_losing_score:'最好落败分',average_margin:'前两名平均分差',margin_samples:'可比较分差局数',tied_score_play_count:'有同分的局数',missing_scores:'缺失成绩数量'}));if(r.rounds)sections.push({key:'rounds',label:'平均轮数',value:F.number(r.rounds.average),caption:`记录 ${r.rounds.known_play_count} 局 / 缺失 ${r.rounds.missing_play_count} 局`});}
    const resultGroups=Object.entries(r.results_by_mode||{}).map(([key,v])=>({key,label:(MODES.find(m=>m.value===key)||{}).label,value:F.percent(v.win_rate??v.success_rate),caption:`已知样本 ${v.eligible_samples??v.eligible_games??0}，未知 ${v.unknown_samples??0}`}));
    this.setData({cards:metrics(r),primaryCards:metrics(r).slice(0,4),secondaryCards:metrics(r).slice(4),rows,detailSections:sections,resultGroups,nextCursor:r.next_cursor||null,emptyReason:'',definition:r.definition_version,showRules:NEED_GAME.has(metric),filterNote:metric==='wanted'?'按活动提名人次和场次统计，只使用人员范围、时间与活动筛选。':metric==='trends'&&q.period==='all'?'趋势默认展示最近 12 个月。':'统计只计公开且符合口径的记录；原始空白保持未知。'});
    if(metric==='overview'&&!more){this.setData({overviewTrend:[],overviewTop:[],overviewExtraError:''});const extras=await Promise.allSettled([api.get('/boardgame-stats/trends',{...q,limit:12}),api.get('/boardgame-stats/most-played',{...q,limit:3})]);if(generation!==this._generation)return;const format=(result,type)=>{if(result.status!=='fulfilled')return [];let rows=result.value.items.map((r,i)=>rowView(r,type,i));const max=Math.max(1,...rows.map(r=>r.numeric));return rows.map(r=>({...r,bar:Math.max(0,r.numeric/max*100)}));};this.setData({overviewTrend:format(extras[0],'trends'),overviewTop:format(extras[1],'most-played'),overviewExtraError:extras.some(r=>r.status==='rejected')?'部分概览暂未加载，点击重新加载':''});}
  }catch(e){if(generation===this._generation)this.setData({error:api.message(e)});}finally{if(generation===this._generation)this.setData({loading:false});}},
 openMetrics(){this.setData({metricOpen:true});},closeMetrics(){this.setData({metricOpen:false});},chooseMetric(e){const i=METRICS.findIndex(m=>m.value===e.currentTarget.dataset.metric);if(i<0)return;this.setData({metricOpen:false});return this.metricChange({detail:{value:i}});},
 metricChange(e){const i=Number(e.detail.value);this.setData({metricIndex:i,metric:METRICS[i].value,nextCursor:null,rows:[],cards:[],detailSections:[],resultGroups:[]});return this.load();},scope(e){this.setData({'query.scope':e.currentTarget.dataset.value});this.load();},
 mode(e){const i=Number(e.detail.value);this.setData({modeIndex:i,'query.mode':MODES[i].value,'query.comparison_key':null,'query.sheet_comparison_key':null});this.load();},
 group(e){const i=Number(e.detail.value);this.setData({groupIndex:i,'query.comparison_key':this.data.groups[i].comparison_key,'query.sheet_comparison_key':null});this.load();},sheetGroup(e){const i=Number(e.detail.value);this.setData({sheetGroupIndex:i,'query.sheet_comparison_key':this.data.sheetGroups[i].sheet_comparison_key});this.load();},
 distribution(e){const i=Number(e.detail.value);this.setData({distributionIndex:i,'query.dimension':['weekday','player_count','environment'][i]});this.load();},bucket(e){const i=Number(e.detail.value);this.setData({bucketIndex:i,'query.bucket':['month','quarter','year','activity'][i]});this.load();},
 openFilters(){this.setData({filterOpen:true});},closeFilters(){this.setData({filterOpen:false});},applyFilters(e){this.setData({query:e.detail.query,filterOpen:false});this.load();},
 async openGames(){this.setData({gameOpen:true});await this.searchGame();},closeGames(){this.setData({gameOpen:false});},gameInput(e){this.setData({gameSearch:e.detail.value});},async searchGame(e){const more=!!(e&&e.currentTarget&&e.currentTarget.dataset.more);try{const r=await api.get('/boardgames',{q:this.data.gameSearch,limit:50,cursor:more?this.data.gameCursor:null});this.setData({games:more?[...this.data.games,...r.items]:r.items,gameCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}},chooseGame(e){const id=Number(e.currentTarget.dataset.id)||null;this.setData({'query.game_id':id,'query.comparison_key':null,'query.sheet_comparison_key':null,gameOpen:false,gameName:id?this.data.gameName:'全部游戏'});this.load();},
 async drill(e){const d=e.currentTarget.dataset.drill,row=e.currentTarget.dataset.row;if(row&&row.play_id)return wx.navigateTo({url:`/pages/boardgame_play/boardgame_play?id=${row.play_id}`});if(!d)return;
  if(d.path.startsWith('/boardgame-stats/wanted/')){try{this._sourceQuery=d;const r=await api.get(d.path,d.query);this.setData({sources:r.items,sourcesOpen:true,sourcesCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}return;}wx.navigateTo({url:F.link('boardgame_history',d.query)});},async moreSources(){try{const r=await api.get(this._sourceQuery.path,{...this._sourceQuery.query,cursor:this.data.sourcesCursor});this.setData({sources:[...this.data.sources,...r.items],sourcesCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}},closeSources(){this.setData({sourcesOpen:false});},activity(e){wx.navigateTo({url:`/pages/boardgame_activity/boardgame_activity?id=${e.currentTarget.dataset.id}`});},history(){wx.navigateTo({url:F.link('boardgame_history',this.data.query)});}
});
