const api=require('../../services/boardgames'),F=require('../../utils/boardgameFilters'),offline=require('../../services/boardgameOffline');
function money(v){return v===null||v===undefined?'未计算':Number(v).toFixed(2);}
Page({data:{dateOpen:false,dateField:'from',dateValue:'',tab:'overview',summary:null,costs:[],currencies:[],tags:[],filters:[],loading:false,saving:false,error:'',notice:'',query:{period:'all'},nextCursor:null,
 periods:F.PERIODS,periodIndex:0,form:{year:new Date().getFullYear(),month:new Date().getMonth()+1,quarter:Math.floor(new Date().getMonth()/3)+1},tagOpen:false,tagName:'',tagId:null,tagRevision:null,
 savedEditOpen:false,savedEdit:null,savedEditName:'',savedEditAction:'rename',linkKind:null,linkId:null,linkHash:null,selectedTags:[],contextName:'',savedCursor:null,tagCursor:null,includeArchived:false},
 onLoad(o){const gameId=Number(o.game_id),playId=Number(o.play_id);if(gameId)this.setData({'query.game_id':gameId,linkKind:'games',linkId:gameId});if(playId)this.setData({linkKind:'plays',linkId:playId,tab:'tags'});},onShow(){this.load();},
 async load(){this.setData({loading:true,error:''});try{const [summary,tags,saved]=await Promise.all([api.get('/boardgame-collection/overview'),api.get('/boardgame-tags',{limit:100,include_archived:this.data.includeArchived}),api.get('/boardgame-saved-filters',{limit:100})]);this.setData({summary,coverage:F.percent(summary.coverage),tags:tags.items,filters:saved.items,tagCursor:tags.next_cursor,savedCursor:saved.next_cursor});if(this.data.linkId){const r=await api.get(`/boardgame-tags/${this.data.linkKind}/${this.data.linkId}`);const name=this.data.linkKind==='games'?await api.get(`/boardgames/${this.data.linkId}`):await api.get(`/boardgame-plays/${this.data.linkId}`);this.setData({linkHash:r.revision_hash,selectedTags:r.items.map(t=>t.id),contextName:name.name||name.game_snapshot.name});this.markTags();}if(this.data.tab==='costs')await this.loadCosts();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({loading:false});}},
 tab(e){this.setData({tab:e.currentTarget.dataset.tab});if(this.data.tab==='costs')this.loadCosts();},
 async loadCosts(more=false){more=more===true;this.setData({loading:true,error:''});try{const r=await api.get('/boardgame-collection/costs',{...this.data.query,limit:20,cursor:more?this.data.nextCursor:null});const names=await Promise.all(r.items.map(i=>api.get(`/boardgames/${i.game_id}`)));const items=r.items.map((r,i)=>({...r,name:names[i].name,price:money(r.purchase_price),cost:money(r.cost_per_play),costHour:money(r.cost_per_hour),costPerson:money(r.cost_per_person),costPersonHour:money(r.cost_per_person_hour)}));this.setData({costs:more?[...this.data.costs,...items]:items,currencies:r.currencies.map(c=>({...c,total:money(c.purchase_total),cost:money(c.cost_per_play),costHour:money(c.cost_per_hour),costPerson:money(c.cost_per_person)})),nextCursor:r.next_cursor,unpriced:r.unpriced_copy_count});}catch(e){this.setData({error:api.message(e)});}finally{this.setData({loading:false});}},
 onReachBottom(){if(this.data.tab==='costs'&&this.data.nextCursor&&!this.data.loading)this.loadCosts(true);},openDate(e){const key=e.currentTarget.dataset.key;this.setData({dateOpen:true,dateField:key,dateValue:this.data.form[key]||api.today()});},closeDate(){this.setData({dateOpen:false});},dateConfirm(e){this.setData({[`form.${this.data.dateField}`]:e.detail.dateValue,dateOpen:false});},
period(e){const i=Number(e.detail.value);this.setData({periodIndex:i,'query.period':F.PERIODS[i].value});},field(e){this.setData({[`form.${e.currentTarget.dataset.key}`]:e.detail.value});},applyPeriod(){const q=F.clean({...this.data.query,...this.data.form});['year','month','quarter'].forEach(k=>{if(q[k])q[k]=Number(q[k]);});this.setData({query:q});this.loadCosts();},
 drill(e){const key=e.currentTarget.dataset.key;if(key){const q=this.data.summary.drilldowns[key].query;return wx.navigateTo({url:F.link('boardgames',q)});}wx.navigateTo({url:F.link('boardgame_history',e.currentTarget.dataset.query)});},game(e){wx.navigateTo({url:`/pages/boardgame_detail/boardgame_detail?id=${e.currentTarget.dataset.id}`});},
 markTags(){this.setData({tags:this.data.tags.map(t=>({...t,selected:this.data.selectedTags.includes(t.id)}))});},selectTag(e){if(!this.data.linkId)return;const id=Number(e.currentTarget.dataset.id),selected=this.data.selectedTags;if(!selected.includes(id)&&this.data.tags.find(t=>t.id===id)?.is_active===false)return this.setData({error:'请先恢复这个标签，再关联记录'});this.setData({selectedTags:selected.includes(id)?selected.filter(i=>i!==id):[...selected,id]});this.markTags();},
 async saveLinks(){if(this.data.saving)return;this.setData({saving:true,error:''});try{const r=await offline.mutate(this.data.linkKind==='games'?'game_tags.put':'play_tags.put',this.data.linkId,{expected_hash:this.data.linkHash,tag_ids:this.data.selectedTags});if(!r.queued)this.setData({linkHash:r.revision_hash});this.setData({notice:r.queued?'已在本机保存，联网后同步':'标签已保存'});}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 openTag(e){const id=Number(e.currentTarget.dataset.id),tag=this.data.tags.find(t=>t.id===id);this._tagKey=api.uuid();this.setData({tagOpen:true,tagId:id||null,tagName:tag?tag.name:'',tagRevision:tag?tag.revision:null});},closeTag(){if(!this.data.saving)this.setData({tagOpen:false});},tagInput(e){this._tagKey=api.uuid();this.setData({tagName:e.detail.value});},
 async saveTag(){if(this.data.saving)return;this.setData({saving:true,error:''});try{await api.send('/boardgame-tags'+(this.data.tagId?`/${this.data.tagId}`:''),this.data.tagId?'PATCH':'POST',{name:this.data.tagName,...(this.data.tagId?{expected_revision:this.data.tagRevision}:{})},this._tagKey);this.setData({tagOpen:false});await this.load();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 async archiveTag(e){const t=this.data.tags.find(t=>t.id===Number(e.currentTarget.dataset.id));if(!t)return;try{await api.send(`/boardgame-tags/${t.id}`,'PATCH',{expected_revision:t.revision,is_active:!t.is_active});await this.load();}catch(e){this.setData({error:api.message(e)});}},showArchived(e){this.setData({includeArchived:e.detail.value});this.load();},
 openSavedEdit(e){const selected=this.data.filters.find(f=>f.id===Number(e.currentTarget.dataset.id));if(selected)this.setData({savedEditOpen:true,savedEdit:selected,savedEditName:selected.name,savedEditAction:e.currentTarget.dataset.action,error:''});},closeSavedEdit(){if(!this.data.saving)this.setData({savedEditOpen:false});},savedEditName(e){this.setData({savedEditName:e.detail.value});},
 async saveSavedEdit(){if(this.data.saving)return;this.setData({saving:true,error:''});try{const row=this.data.savedEdit,remove=this.data.savedEditAction==='delete';if(!remove&&!this.data.savedEditName.trim())throw new Error('请填写筛选名称');await api.send(`/boardgame-saved-filters/${row.id}`,remove?'DELETE':'PATCH',{expected_revision:row.revision,...(remove?{}:{name:this.data.savedEditName.trim()})});this.setData({savedEditOpen:false});await this.load();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 applySaved(e){const s=this.data.filters.find(f=>f.id===Number(e.currentTarget.dataset.id));if(s)wx.navigateTo({url:F.link(s.target==='games'?'boardgames':s.target==='plays'?'boardgame_history':'boardgame_stats',s.query)});},
 async more(e){const kind=e.currentTarget.dataset.kind,path=kind==='tags'?'/boardgame-tags':'/boardgame-saved-filters';try{const r=await api.get(path,{limit:100,cursor:this.data[kind==='tags'?'tagCursor':'savedCursor'],...(kind==='tags'?{include_archived:this.data.includeArchived}:{})});this.setData({[kind]:[...this.data[kind],...r.items],[kind==='tags'?'tagCursor':'savedCursor']:r.next_cursor});this.markTags();}catch(e){this.setData({error:api.message(e)});}}
});
