/* Page-controller/API integration. This does not emulate native rendering. */
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const input=JSON.parse(fs.readFileSync(0,'utf8')),root=path.resolve(__dirname,'../..');
const storage=new Map([['userId',input.userId],['userNickname','合成成员'],['userRole','user'],['accessToken','synthetic-local-bridge']]);
const failures=[],navigations=[],requests=[];const plain=v=>JSON.parse(JSON.stringify(v));
const wx={getStorageSync:k=>storage.get(k)||'',setStorageSync:(k,v)=>storage.set(k,plain(v)),removeStorageSync:k=>storage.delete(k),onNetworkStatusChange(){},
 setNavigationBarTitle(){},showToast(){},navigateBack(){},navigateTo:o=>navigations.push(o.url),stopPullDownRefresh(){},
 request(o){requests.push({url:o.url,method:o.method,data:o.data});fetch(o.url,{method:o.method||'GET',headers:o.header,body:o.data===undefined?undefined:JSON.stringify(o.data)})
 .then(async r=>{const text=await r.text(),data=text?JSON.parse(text):null;if(!r.ok)failures.push({url:o.url,status:r.status,reason:data&&data.details&&data.details.reason});o.success({statusCode:r.status,data,header:{}});}).catch(e=>o.fail({errMsg:e.message}));}};
const cache=new Map();
function moduleAt(file,onPage){if(cache.has(file)&&!onPage)return cache.get(file);if(file.endsWith('/services/config.js'))return {getApiBaseUrl:()=>input.base+'/api/v1'};if(file.endsWith('/services/logger.js'))return {createTraceId:()=> 'synthetic-test',logInfo(){},logError(){},summarizeError(){},logRequestTransportFail(){}};
 const module={exports:{}},sandbox={module,exports:module.exports,wx,Promise,Map,Set,Date,Math,Error,JSON,console,setTimeout,clearTimeout,setInterval,clearInterval,
 require:n=>moduleAt(path.resolve(path.dirname(file),n.endsWith('.js')?n:n+'.js')),Page:onPage,Component(){}};
 vm.runInNewContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});cache.set(file,module.exports);return module.exports;}
function setPath(obj,k,v){if(v===undefined)throw new Error('undefined setData: '+k);const keys=k.replace(/\[(\d+)\]/g,'.$1').split('.');let target=obj;keys.slice(0,-1).forEach((s,i)=>{if(target[s]===undefined)target[s]=/^\d+$/.test(keys[i+1])?[]:{};target=target[s];});target[keys.at(-1)]=plain(v);}
function page(name,options={}){let def;moduleAt(path.join(root,'pages',name,name+'.js'),v=>def=v);const p={...def,data:plain(def.data)};p.setData=v=>Object.entries(v).forEach(([k,v])=>setPath(p.data,k,v));if(p.onLoad)p.onLoad(options);return p;}
function ok(p,label){assert.equal(p.data.error||p.data.formError||'', '',label+': '+(p.data.error||p.data.formError||''));}
const layouts={};function capture(name,page){layouts[name]={page:name.split('--')[0],data:plain(page.data)};}
const event=(dataset={},value)=>({currentTarget:{dataset},detail:{value}});
async function run(){
 const api=moduleAt(path.join(root,'services/boardgames.js'));
 const game=await api.send('/boardgames','POST',{name:'联调合成桌游',set_overrides:{min_players:2,max_players:4}});
 const library=page('boardgames');await library.reload();ok(library,'library');assert.ok(library.data.games.some(g=>g.id===game.id));capture('boardgames',library);
 const detail=page('boardgame_detail',{id:String(game.id)});await detail.load();ok(detail,'detail');capture('boardgame_detail',detail);
 const play=page('boardgame_play',{game_id:String(game.id)});await play.load();ok(play,'play initial');
 await play.openLocations();play.locationInput(event({},'联调常用地点'));await play.createLocation();assert.equal(play.data.locationError,'');assert.ok(play.data.form.location_id);
 play.openStart();play.dateConfirm({detail:{dateValue:'2026-09-01',timeValue:'18:30'}});assert.equal(play.data.form.started_at,'2026-09-01T18:30:00+08:00');assert.equal(play.data.form.started_at_label,'2026-09-01 18:30');
 const forms=moduleAt(path.join(root,'utils/boardgamePlayForm.js'));play.applyForm({...play.data.form,players:[forms.member({id:input.userId,nickname:'合成甲'},1),forms.member({id:input.secondUserId,nickname:'合成乙'},2)]},{dirty:true});
 play.modeChange(event({},0));capture('boardgame_play--entry',play);play.playerField(event({index:0,key:'score'},0));play.statusChange(event({index:1},2));await play.save(event({status:'completed'}));ok(play,'save native gave-up');
 assert.ok(play.data.id);assert.equal(play.data.play.players[1].outcome,'loss');assert.equal(play.data.play.players[0].score,'0.000');play.stopTicker();capture('boardgame_play--result',play);
 const sheetPage=page('boardgame_scoresheet',{id:String(play.data.id)});await sheetPage.load();ok(sheetPage,'scoresheet load');sheetPage.setData({reason:'补充合成分项'});await sheetPage.useTemplate(event());ok(sheetPage,'from template');
 const group=sheetPage._sheet.groups[0],subject=sheetPage._sheet.subjects[0];sheetPage.updateCell(group.rows[0].key,subject.key,{expression:'2 + 3'});await sheetPage.preview();ok(sheetPage,'sheet preview');await sheetPage.save();ok(sheetPage,'sheet save');capture('boardgame_scoresheet',sheetPage);
 const history=page('boardgame_history',{game_id:String(game.id)});await history.load();ok(history,'history');assert.ok(history.data.items.length);capture('boardgame_history',history);
 const stats=page('boardgame_stats',{game_id:String(game.id)});for(const metric of ['overview','most-played','wanted','players','detailed','streaks','variants']){await stats.chooseMetric(event({metric}));ok(stats,'stats '+metric);if(['overview','players'].includes(metric))capture('boardgame_stats--'+metric,stats);}
 stats.setData({'query.comparison_key':stats.data.groups[1].comparison_key,metric:'score-curve'});await stats.load();ok(stats,'curve');
 const collection=page('boardgame_collection',{game_id:String(game.id)});await collection.load();ok(collection,'collection');capture('boardgame_collection',collection);collection.openTag(event());collection.setData({tagName:'联调标签'});await collection.saveTag();ok(collection,'tag create');collection.selectTag(event({id:collection.data.tags[0].id}));await collection.saveLinks();ok(collection,'tag links');await collection.loadCosts();ok(collection,'costs');
 storage.set('accessToken','synthetic-admin-bridge');const expansion=await api.send('/boardgames','POST',{name:'联调合成扩展',game_type:'expansion'});await api.send(`/boardgames/${game.id}/expansions/${expansion.id}`,'PUT',{expected_revision:0,manual_decision:'block'});storage.set('accessToken','synthetic-local-bridge');
 const activity=page('boardgame_activity',{id:String(input.activityId)});await activity.load();ok(activity,'activity');await activity.add(event({kind:'nomination'}));ok(activity,'activity game picker');await activity.chooseGame(event({id:game.id}));activity.expansion(event({id:expansion.id},true));activity.expansionNote(event({id:expansion.id},'只用模块一'));activity.expansionNote(event({id:expansion.id,key:'compatibility_note'},'已确认自定义兼容玩法'));capture('boardgame_activity--nomination',activity);await activity.save();ok(activity,'nomination save');assert.equal(activity.data.summary.nominations.length,1);capture('boardgame_activity',activity);await activity.people(event({id:game.id}));assert.equal(activity.data.people[0].expansions[0].game_name,expansion.name);assert.equal(activity.data.people[0].expansions[0].modules_note,'只用模块一');capture('boardgame_activity--people',activity);activity.closePeople();
 // Exercise the exact UI path after withdrawing: no database-only revision lookup.
 await activity.withdraw(event({id:game.id}));ok(activity,'withdraw nomination');assert.equal(activity.data.summary.nominations.length,0);
 await activity.add(event({kind:'nomination'}));await activity.chooseGame(event({id:game.id}));assert.ok(activity.data.form.expected_revision>1);
 await activity.save();ok(activity,'explicit re-nomination');assert.equal(activity.data.summary.nominations[0].nomination_count,1);
 const blockedPlay=page('boardgame_play',{game_id:String(game.id),activity_id:String(input.activityId),from_nomination:'1',quick_start:'1'});
 await blockedPlay.load();assert.match(blockedPlay.data.error,/签到/);assert.equal(blockedPlay.data.form,null);
 storage.set('accessToken','synthetic-admin-bridge');
 const activityDetail=await api.get(`/activities/${input.activityId}`),participant=activityDetail.participants.find(p=>p.user_id===input.userId);
 await api.send(`/activities/${input.activityId}/participants/${participant.id}/admin-checkin`,'POST');
 storage.set('accessToken','synthetic-local-bridge');await activity.load();assert.equal(activity.data.summary.permissions.can_record,true);
 activity.record(event({kind:'nomination',id:game.id}));
 const nominationOptions=Object.fromEntries(new URL('http://local.invalid'+navigations.at(-1)).searchParams);
 const nominationPlay=page('boardgame_play',nominationOptions);await nominationPlay.load();ok(nominationPlay,'nomination quick record');
 assert.equal(nominationPlay.data.form.activity_id,input.activityId);assert.equal(nominationPlay.data.form.plan_id,null);
 assert.equal(nominationPlay.data.form.expansions[0].modules_note,'只用模块一');assert.equal(nominationPlay.data.form.expansions[0].compatibility_note,'已确认自定义兼容玩法');
 assert.equal(nominationPlay.data.activityContext.name,activityDetail.name);assert.equal(nominationPlay.data.timingOpen,true);
 await nominationPlay.timer(event({action:'start'}));ok(nominationPlay,'activity play start timer');assert.equal(nominationPlay.data.play.status,'draft');
 assert.equal(nominationPlay.data.play.timer_status,'running');assert.equal(nominationPlay.data.play.activity_id,input.activityId);
 await nominationPlay.timer(event({action:'pause'}));ok(nominationPlay,'activity play pause');nominationPlay.stopTicker();
 const imports=page('boardgame_imports',{id:input.jobId});await imports.load();ok(imports,'imports');capture('boardgame_imports',imports);const source=imports.data.items.find(i=>i.source_kind==='bgstats_play');await imports.review(event({id:source.id}));ok(imports,'import preview');assert.ok(imports.data.review.applied_plays.length);capture('boardgame_imports--review',imports);await imports.openMappings();ok(imports,'mappings');await imports.openReport();ok(imports,'report');
 const privatePlay=imports.data.review.applied_plays[0];const raw=await api.get(`/boardgame-imports/${input.jobId}/items/${source.id}/plays/${privatePlay.id}`);assert.equal(raw.play.id,privatePlay.id);
 await imports.openPicker(event({kind:'location'}));ok(imports,'source location picker');assert.ok(imports.data.pickerItems.some(p=>p.label==='联调常用地点'));
 const copy=imports.data.items.find(i=>i.source_kind==='bgstats_copy');await imports.review(event({id:copy.id}));ok(imports,'copy review');imports.setData({inventoryOverride:true});imports.inventoryField(event({key:'purchase_price'},'0'));imports.inventoryField(event({key:'purchase_currency'},'CNY'));imports.inventoryField(event({key:'purchased_on'},'2026-01-02'));await imports.saveDecision(event());ok(imports,'reviewed source copy');
 const offlinePage=page('boardgame_offline');offlinePage.reload();ok(offlinePage,'offline empty');assert.equal(offlinePage.data.items.length,0);capture('boardgame_offline',offlinePage);
 // Management pages use real HTTP permissions, revision checks and preview hashes.
 await play.load();play.openAction(event({action:'report'}));play.actionReason(event({},'合成反馈：核对本局日期'));await play.saveAction();assert.equal(play.data.actionError,'');
 const manage=page('boardgame_manage');await manage.load();ok(manage,'reports list');assert.ok(manage.data.rows.length);capture('boardgame_manage--reports',manage);manage.openAction(event({id:manage.data.rows[0].id,action:'resolve'}));manage.field(event({key:'resolution'},'经核对日期正确，无需修改'));await manage.save();ok(manage,'resolve report');assert.equal(manage.data.rows.length,0);
 const owned=await api.send('/boardgame-inventory','POST',{game_id:game.id,owner_user_id:input.userId});const ownBox=owned.items[0];manage.onLoad({kind:'inventory',game_id:String(game.id)});await manage.load();ok(manage,'own inventory');
 manage.openAction(event({id:ownBox.id,action:'archive'}));manage.field(event({key:'reason'},'合成归档'));await manage.save();ok(manage,'archive inventory');manage.setData({archived:true});await manage.load();manage.openAction(event({id:ownBox.id,action:'restore'}));manage.field(event({key:'reason'},'重新启用'));await manage.save();ok(manage,'restore inventory');
 const favorite=await api.send('/boardgame-saved-filters','POST',{name:'合成常用筛选',target:'games',query:{owned:true}});await collection.load();collection.openSavedEdit(event({id:favorite.id,action:'rename'}));collection.savedEditName(event({},'已更名筛选'));await collection.saveSavedEdit();ok(collection,'rename saved filter');collection.openSavedEdit(event({id:favorite.id,action:'delete'}));capture('boardgame_collection--saved-filter',collection);await collection.saveSavedEdit();ok(collection,'delete saved filter');
 storage.set('userRole','admin');storage.set('accessToken','synthetic-admin-bridge');storage.set('userId',input.adminUserId);
 await activity.load();await activity.add(event({kind:'plan'}));await activity.chooseGame(event({id:game.id}));activity.expansion(event({id:expansion.id},true));activity.expansionNote(event({id:expansion.id,key:'compatibility_note'},'已核对版本'));activity.expansionNote(event({id:expansion.id},'模块二'));await activity.save();ok(activity,'plan expansion save');await activity.editPlan(event({id:activity.data.summary.plans[0].id}));await activity.save();ok(activity,'plan expansion resave');assert.equal(activity.data.summary.plans[0].expansions[0].game_name,expansion.name);activity.setData({tab:'plans'});capture('boardgame_activity--plans',activity);
 activity.record(event({kind:'plan',id:activity.data.summary.plans[0].id}));
 const planOptions=Object.fromEntries(new URL('http://local.invalid'+navigations.at(-1)).searchParams),plannedPlay=page('boardgame_play',planOptions);
 await plannedPlay.load();ok(plannedPlay,'plan quick record');assert.equal(plannedPlay.data.form.plan_id,activity.data.summary.plans[0].id);
 assert.equal(plannedPlay.data.form.expansions[0].modules_note,'模块二');await plannedPlay.save(event({status:'draft'}));ok(plannedPlay,'planned draft save');
 assert.equal(plannedPlay.data.play.activity_id,input.activityId);assert.equal(plannedPlay.data.play.plan_id,activity.data.summary.plans[0].id);plannedPlay.stopTicker();
 const organizerNomination=page('boardgame_play',nominationOptions);await organizerNomination.load();ok(organizerNomination,'other member nomination');
 assert.equal(organizerNomination.data.form.expansions.length,0); // Do not combine other people's requested modules into actual play data.
 sheetPage.setData({isAdmin:true});await sheetPage.load();sheetPage.openMaintenance(event({kind:'template'}));capture('boardgame_scoresheet--template',sheetPage);await sheetPage.saveMaintenance();ok(sheetPage,'create versioned template');sheetPage.openMaintenance(event({kind:'review'}));sheetPage.maintenanceField(event({key:'maintenanceReason'},'确认计分含义与可比较范围'));await sheetPage.saveMaintenance();ok(sheetPage,'review statistics structure');
 const mergeSource=await api.send('/boardgames','POST',{name:'管理联调重复游戏'}),mergeTarget=await api.send('/boardgames','POST',{name:'管理联调保留游戏'});
 manage.onLoad({kind:'games'});manage.setData({archived:false});await manage.load();manage.openAction(event({id:mergeSource.id,action:'merge'}));await manage.openPicker();await manage.choose(event({id:mergeTarget.id}));assert.ok(manage.data.preview);capture('boardgame_manage--'+manage.data.action,manage);manage.field(event({key:'reason'},'已核对为同一款'));await manage.save();ok(manage,'merge game');
 manage.onLoad({kind:'inventory',game_id:String(game.id)});await manage.load();manage.openAction(event({id:ownBox.id,action:'correct'}));await manage.openPicker();await manage.choose(event({id:mergeTarget.id}));assert.ok(manage.data.preview);capture('boardgame_manage--'+manage.data.action,manage);manage.field(event({key:'reason'},'核对实体盒面，更正游戏'));await manage.save();ok(manage,'correct inventory');
 storage.set('userRole','user');storage.set('accessToken','synthetic-local-bridge');storage.set('userId',input.userId);
 await play.load();await play.openHistory();assert.equal(play.data.actionError,'');assert.ok(play.data.historyRows.length);play.closeHistory();play.openAction(event({action:'void'}));play.actionReason(event({},'合成作废验收'));capture('boardgame_play--void',play);await play.saveAction();assert.equal(play.data.actionError,'');assert.equal(play.data.play.status,'voided');play.openAction(event({action:'restore'}));play.actionReason(event({},'恢复后重新核对'));await play.saveAction();assert.equal(play.data.actionError,'');assert.equal(play.data.play.status,'draft');play.stopTicker();
 const multi=page('boardgame_imports',{id:input.segmentJobId});await multi.load();ok(multi,'multi import load');const multiItem=multi.data.items.find(i=>i.source_kind==='bgg_play');await multi.review(event({id:multiItem.id}));ok(multi,'multi preview');multi.setData({game,acknowledged:true});for(const person of multi.data.decisionPlayers)if(!person.is_anonymous)multi.keepUnmatched(event({slot:person.source_slot}));
 for(let i=0;i<2;i++){await multi.editSegment(event({index:i}));ok(multi,'open segment');const segment=page('boardgame_play',{segment_key:multi.data.segmentKey,segment_index:String(i)});await segment.load();ok(segment,'segment load');capture('boardgame_play--segment',segment);assert.ok(segment.data.segmentMode);assert.ok(segment.data.form.players.every(p=>p.score===null));segment.field(event({key:'duration_minutes'},String(i?50:20)));await segment.save(event({status:'completed'}));ok(segment,'segment save');segment.stopTicker();}
 multi.setData({segments:moduleAt(path.join(root,'services/boardgameImportSegments.js')).summary(moduleAt(path.join(root,'services/boardgameImportSegments.js')).read(multi.data.segmentKey))});capture('boardgame_imports--segments',multi);
 await multi.saveDecision(event());ok(multi,'multi decision apply');assert.equal(multi.data.reviewOpen,false);
 const noSheet404=failures.filter(f=>f.status===404&&f.url.endsWith('/scoresheet'));assert.equal(failures.length,noSheet404.length,JSON.stringify(failures));
 if(input.layoutDir){fs.mkdirSync(input.layoutDir,{recursive:true});fs.writeFileSync(path.join(input.layoutDir,'controller-states.json'),JSON.stringify(layouts,null,2));}
 console.log(JSON.stringify({status:'passed',controllerPages:11,requests:requests.length,expectedMissingSheets:noSheet404.length}));
}
run().catch(e=>{console.error(e.message);process.exitCode=1;});
