(() => {
  const root = document.getElementById('dragon-boardgame-flow');
  const screen = root.querySelector('.dr-screen'), overlay = root.querySelector('[data-overlay]'), bottom = root.querySelector('[data-bottom]');
  const covers = JSON.parse(document.getElementById('dragon-game-covers').textContent);
  const games = [
    {id:1,name:'工业革命：伯明翰',en:'Brass: Birmingham',players:'2–4 人',time:'60–120 分钟',cover:covers.brass,owned:true,available:true},
    {id:2,name:'火星改造计划',en:'Terraforming Mars',players:'1–5 人',time:'120 分钟',cover:covers.mars,owned:false,available:false}
  ];
  const members = [{id:1,name:'小李（我）',short:'李'},{id:2,name:'小陈',short:'陈'},{id:3,name:'小赵',short:'赵'},{id:4,name:'小吴',short:'吴'}];
  const activities = [{id:1,name:'周末桌游局',date:'2026-09-13'},{id:2,name:'月末聚会',date:'2026-08-23'}];
  const labels = {unrecorded:'未填写',recorded:'已记分',gave_up:'摆烂不算分了',unfinished:'没开完',table_flip:'掀桌了'};
  const modes = {individual:'个人竞技',team:'团队竞技',cooperative:'合作',solo:'单人',unscored:'只记游玩'};
  const fresh = () => ({game:1,selected:[1,2,3],scores:{1:'78',2:'0',3:''},statuses:{1:'recorded',2:'recorded',3:'unrecorded'},teams:{1:1,2:2,3:1,4:2},teamScores:{1:'80',2:'60'},teamStatuses:{1:'recorded',2:'recorded'},sharedScore:'',sharedStatus:'unrecorded',sharedResult:'unknown',mode:'individual',end:'completed',date:'2026-09-13',activity:1,expanded:false,draft:false,resultMethod:'score',winnerIds:[],resultReason:''});
  const records = [
    {...fresh(),id:1,date:'2026-09-06',scores:{1:'78',2:'62',3:'54'},statuses:{1:'recorded',2:'recorded',3:'recorded'}},
    {...fresh(),id:2,game:2,date:'2026-08-23',activity:2,scores:{1:'',2:'',3:''},statuses:{1:'unrecorded',2:'unrecorded',3:'unrecorded'}},
    {...fresh(),id:3,date:'2026-07-12',activity:0,selected:[2,3],scores:{2:'82',3:'72'},statuses:{2:'recorded',3:'recorded'}}
  ];
  const nominations = [{game:1,activity:1,people:[2,3,4]},{game:2,activity:2,people:[1,2]}];
  const state = {page:'library',game:1,detail:'info',scope:'all',period:'quarter',activityIds:[],gameFilter:null,start:'2026-07-01',end:'2026-09-30',owned:false,available:false,search:'',recent:true,checked:true,organizer:false,started:false,imported:false,mappings:{},selectedRecord:1};
  let form = fresh(), stack = [], draftSelection = [], nominateAction = 'nominate', previousFocus;
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const game = id => games.find(g => g.id === id) || games[0];
  const member = id => members.find(m => m.id === id);
  const activityName = id => activities.find(a => a.id === id)?.name || '独立记录';
  const button = (label, action, extra='') => `<button type="button" class="dr-button" data-action="${action}" ${extra}>${label}</button>`;
  const primary = (label, action) => `<button type="button" class="dr-button dr-primary" data-action="${action}">${label}</button>`;
  const titleRow = (name, action, label) => `<div class="dr-h"><h2>${name}</h2>${action?`<button type="button" data-action="${action}">${label}</button>`:''}</div>`;
  const tabs = (items, selected, attr) => `<div class="dr-tabs">${items.map(([v,n])=>`<button type="button" ${attr}="${v}" aria-pressed="${selected===v}">${n}</button>`).join('')}</div>`;
  function close() { overlay.hidden=true;overlay.innerHTML='';root.querySelector('.dr-screen').inert=false;root.querySelector('.dr-head').inert=false;root.querySelector('.dr-nav').inert=false;bottom.inert=false;if(previousFocus?.isConnected)previousFocus.focus(); }
  function navigate(page) { if(page!==state.page)stack.push(state.page);state.page=page;close();render(); }
  function sheet(title, content, isForm=false, actions='') {
    previousFocus=document.activeElement;
    overlay.hidden=false;
    overlay.innerHTML=`<div class="dr-mask"><section class="dr-sheet ${isForm?'dr-form-sheet':''}" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="dr-handle"></div><div class="dr-sheet-heading"><h3>${title}</h3><button type="button" class="dr-sheet-close" data-action="close" aria-label="关闭">×</button></div><div class="dr-sheet-content">${content}</div>${actions?`<div class="dr-bottom">${actions}</div>`:''}</section></div>`;
    const panel=overlay.querySelector('.dr-sheet'), view=overlay.querySelector('.dr-sheet-content');
    const styles=getComputedStyle(root),required=76+view.scrollHeight+(actions?80:0)+16;
    const tiers=['low','standard','high'].map(t=>Number.parseFloat(styles.getPropertyValue('--dr-drawer-'+t)));
    panel.style.height=(tiers.find(h=>h>=required)||tiers[2])+'px';
    screen.inert=true;root.querySelector('.dr-head').inert=true;root.querySelector('.dr-nav').inert=true;bottom.inert=true;
    overlay.querySelector('button,input,select')?.focus();
  }
  function error(text) { const target=overlay.hidden?screen:overlay.querySelector('.dr-sheet-content');target.querySelector('[role=alert]')?.remove();const el=document.createElement('p');el.className='dr-alert';el.setAttribute('role','alert');el.textContent=text;target.prepend(el); }
  function personalResult(p,id) {
    if(p.end!=='completed')return '未完成';
    if(p.mode==='unscored')return '已参局';
    if(p.statuses[id]==='gave_up')return '未获胜';
    if(['unfinished','table_flip'].includes(p.statuses[id]))return '结果待补';
    if(['cooperative','solo'].includes(p.mode))return p.sharedStatus==='gave_up'||p.sharedResult==='failure'?'未获胜':p.sharedResult==='success'?'获胜':'结果待补';
    const team=p.mode==='team', ids=team?[...new Set(p.selected.map(x=>p.teams[x]))]:p.selected;
    const statuses=team?p.teamStatuses:p.statuses, scores=team?p.teamScores:p.scores, key=team?p.teams[id]:id;
    if(statuses[key]==='gave_up')return '未获胜';
    if(['unfinished','table_flip'].includes(statuses[key]))return '结果待补';
    if(p.resultMethod&&p.resultMethod!=='score')return (p.winnerIds||[]).includes(Number(key))?'获胜':'未获胜';
    const eligible=ids.filter(x=>statuses[x]!=='gave_up');
    if(eligible.some(x=>statuses[x]!=='recorded'||scores[x]===''))return '结果待补';
    return Number(scores[key])===Math.max(...eligible.map(x=>Number(scores[x])))?'获胜':'未获胜';
  }
  function summary(p) {
    if(p.end!=='completed')return `${p.end==='table_flip'?'掀桌结束':'没开完'} · 保留记录，不计完成局数和胜率`;
    if(p.mode==='unscored')return '保留游玩次数，不产生胜率或分数排名';
    const n=p.selected.filter(id=>p.statuses[id]==='gave_up').length;
    return n?`${n} 位成员摆烂，计为未获胜；分数保持空值`:'未填写保持空值，0 分单独记录；结果未知时不计胜率';
  }
  function inRange(date) { const start={month:'2026-09-01',quarter:'2026-07-01',year:'2026-01-01',all:'0000-01-01',custom:state.start}[state.period];return date>=start&&date<=({month:'2026-09-30',quarter:'2026-09-30',year:'2026-12-31',all:'9999-12-31',custom:state.end}[state.period]); }
  function filtered(gameId=state.gameFilter) { return records.filter(p=>inRange(p.date)&&(!state.activityIds.length||state.activityIds.includes(p.activity))&&(state.scope!=='mine'||p.selected.includes(1))&&(!gameId||p.game===gameId)); }
  function scoreBox(unit,id,name,p=form) {
    const status=unit==='shared'?p.sharedStatus:unit==='team'?p.teamStatuses[id]:p.statuses[id];
    const value=unit==='shared'?p.sharedScore:unit==='team'?p.teamScores[id]:p.scores[id];
    return `<div class="dr-scorebox"><input type="number" step="0.000001" data-score="${id}" data-unit="${unit}" aria-label="${esc(name)}的分数" placeholder="未填" value="${esc(value)}" ${!['recorded','unrecorded'].includes(status)?'disabled':''}><button type="button" class="dr-status" data-score-state="${id}" data-unit="${unit}" aria-label="${esc(name)}的成绩状态">${labels[status]} ▾</button></div>`;
  }
  function playerEditor() {
    const team=form.mode==='team', shared=['cooperative','solo'].includes(form.mode), unscored=form.mode==='unscored';
    let html=`<div class="dr-section">${form.selected.map(id=>`<div class="dr-line"><div class="dr-person"><span class="dr-avatar">${member(id).short}</span><span>${member(id).name}</span></div>${unscored?'':team?`<div class="dr-scorebox"><select class="dr-button" aria-label="${member(id).name}的队伍" data-team="${id}"><option value="1" ${form.teams[id]===1?'selected':''}>1 队</option><option value="2" ${form.teams[id]===2?'selected':''}>2 队</option></select><button class="dr-status" type="button" data-score-state="${id}" data-unit="player">${labels[form.statuses[id]]} ▾</button></div>`:shared?`<button class="dr-status" type="button" data-score-state="${id}" data-unit="player">${labels[form.statuses[id]]} ▾</button>`:scoreBox('player',id,member(id).name)}</div>`).join('')}</div>`;
    if(team)html+=titleRow('队伍成绩')+`<div class="dr-section">${[1,2].map(id=>`<div class="dr-line"><strong>${id} 队</strong>${scoreBox('team',id,`${id} 队`)}</div>`).join('')}</div>`;
    if(shared)html+=titleRow(form.mode==='solo'?'挑战结果':'共同结果')+`<div class="dr-section"><div class="dr-row"><span>共同分数</span>${scoreBox('shared','all','共同')}</div><label class="dr-field"><span>挑战结果</span><select data-shared-result ${form.sharedStatus==='gave_up'?'disabled':''}>${[['unknown','结果待补'],['success','成功'],['failure','失败']].map(([v,n])=>`<option value="${v}" ${form.sharedResult===v?'selected':''}>${n}</option>`).join('')}</select></label></div>`;
    return html;
  }
  function filterBar() { return `<div class="dr-row" style="margin-bottom:12px"><select class="dr-button" aria-label="时间范围" data-period>${[['month','本月'],['quarter','本季度'],['year','本年'],['all','全部时间'],['custom','自定义']].map(([v,n])=>`<option value="${v}" ${state.period===v?'selected':''}>${n}</option>`).join('')}</select>${button(state.activityIds.length?`${state.activityIds.length} 场活动`:'全部活动','activity-filter')}</div>${state.period==='custom'?`<p class="dr-muted">${state.start} 至 ${state.end}</p>`:''}${state.gameFilter?`<div class="dr-row dr-summary"><span>${esc(game(state.gameFilter).name)}</span>${button('清除桌游','clear-game-filter')}</div>`:''}`; }
  function gameCard(g) { return `<button type="button" class="dr-game" data-game="${g.id}">${g.cover?`<img src="${g.cover}" alt="${esc(g.name)}封面">`:`<div class="dr-empty">${esc(g.name.slice(0,4))}</div>`}<div class="dr-booktext"><strong>${esc(g.name)}</strong><div class="dr-muted">${g.players} · ${g.owned?'我有馆藏':'公共资料'}</div></div></button>`; }
  function libraryGames() { return games.filter(g=>(!state.owned||g.owned)&&(!state.available||g.available)&&(g.name+g.en).toLowerCase().includes(state.search.toLowerCase())); }
  function historyRows(gameId=state.gameFilter) { const rows=filtered(gameId);return rows.length?rows.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id).map(p=>`<button type="button" class="dr-section dr-block" style="text-align:left" data-record="${p.id}"><div class="dr-row"><strong>${esc(game(p.game).name)}</strong><span class="dr-tag">${p.draft?'草稿':p.end==='completed'?'已完成':'未完成'}</span></div><p class="dr-muted">${p.date} · ${activityName(p.activity)} · ${p.selected.length} 人</p><span>${p.selected.includes(1)?'我：'+personalResult(p,1):modes[p.mode]}</span></button>`).join(''):'<div class="dr-empty">这个范围内还没有对局记录</div>'; }
  function renderStats() {
    const completed=filtered().filter(p=>!p.draft&&p.end==='completed');
    const ranking=games.map(g=>({g,count:completed.filter(p=>p.game===g.id).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count);
    const wanted=nominations.filter(n=>inRange(activities.find(a=>a.id===n.activity).date)&&(!state.activityIds.length||state.activityIds.includes(n.activity))&&(!state.gameFilter||state.gameFilter===n.game)&&(state.scope!=='mine'||n.people.includes(1)));
    const wantedGroups=games.map(g=>({g,rows:wanted.filter(n=>n.game===g.id)})).filter(x=>x.rows.length).map(x=>({...x,count:x.rows.reduce((sum,n)=>sum+(state.scope==='mine'?1:n.people.length),0)})).sort((a,b)=>b.count-a.count||b.rows.length-a.rows.length);
    const personal=members.map(m=>{const plays=completed.filter(p=>p.game===state.game&&p.mode==='individual'&&p.selected.includes(m.id));const valid=plays.filter(p=>['获胜','未获胜'].includes(personalResult(p,m.id)));const wins=valid.filter(p=>personalResult(p,m.id)==='获胜').length;return {m,n:valid.length,wins};}).filter(x=>x.n&&(state.scope!=='mine'||x.m.id===1)).sort((a,b)=>b.wins/b.n-a.wins/a.n);
    return tabs([['all','全体'],['mine','我的']],state.scope,'data-scope')+filterBar()+`<div class="dr-section"><div class="dr-muted">${state.scope==='mine'?'我的':'全体'}已完成对局</div><div class="dr-metrics">${[[completed.length,'局'],[new Set(completed.map(p=>p.game)).size,'款游戏'],[new Set(completed.map(p=>p.date)).size,'游玩日']].map(([n,s])=>`<div><span class="dr-number">${n}</span><span class="dr-muted">${s}</span></div>`).join('')}</div></div>`+titleRow('开的最多')+`<div class="dr-section">${ranking.length?ranking.map(({g,count})=>`<button type="button" class="dr-option" data-drill="${g.id}"><span>${esc(g.name)}</span><span>${count} 局 ›</span></button><div class="dr-bar"><span style="width:${count/ranking[0].count*100}%"></span></div>`).join(''):'暂无完成对局'}</div>`+titleRow('最想开')+`<div class="dr-section">${wantedGroups.length?wantedGroups.map(({g,rows,count})=>`<button type="button" class="dr-option" data-action="activity"><span>${esc(g.name)}<span class="dr-muted" style="display:block">来自 ${rows.length} 场活动</span></span><span>${count} ${state.scope==='mine'?'次':'人次'} ›</span></button>`).join(''):'这个范围内暂无提名'}</div>`+titleRow('单款成绩')+`<div class="dr-section"><label class="dr-field"><span>桌游 · 个人竞技</span><select data-stats-game>${games.map(g=>`<option value="${g.id}" ${g.id===state.game?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><table><thead><tr><th>玩家</th><th>获胜 / 有效局</th><th>胜率</th></tr></thead><tbody>${personal.map(({m,n,wins})=>`<tr><td>${m.name}</td><td>${wins} / ${n}</td><td>${Math.round(wins/n*100)}%</td></tr>`).join('')||'<tr><td colspan="3">暂无结果明确的对局</td></tr>'}</tbody></table><p class="dr-muted">摆烂计未获胜；未完成整局不进入分母。</p>${button('查看趋势','insights')}</div>`;
  }
  function render() {
    const titles={library:'桌游库',detail:'桌游详情',activity:'活动想玩',editor:'记录对局',plays:'对局记录',playdetail:'对局详情',stats:'桌游统计',imports:'导入记录',mapping:'玩家匹配'};
    root.querySelector('[data-title]').textContent=titles[state.page];root.querySelector('.dr-head [data-action=import]').hidden=!['library','plays'].includes(state.page);bottom.hidden=true;bottom.innerHTML='';
    root.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.page===state.page)));
    if(state.page==='library') {
      screen.innerHTML=`<input class="dr-search" aria-label="搜索桌游" placeholder="搜索名称或别名" data-search value="${esc(state.search)}">`+titleRow('近期录入','add-game','录入桌游')+(state.recent?`<div class="dr-recent"><img src="${covers.brass}" alt="工业革命封面"><div><span class="dr-tag">刚刚加入</span><strong>下一局，玩点什么？</strong><span class="dr-muted">和朋友们挑一款开桌</span></div></div>`:'')+titleRow('全部桌游','filter',state.owned||state.available?'已筛选':'筛选')+`<div class="dr-grid" data-game-grid>${libraryGames().map(gameCard).join('')||'<div class="dr-empty">没有符合条件的桌游</div>'}</div><div class="dr-h">${button('活动里想玩什么','activity')}${button('我的馆藏','my-inventory')}</div>`;
    } else if(state.page==='detail') {
      const g=game(state.game);
      screen.innerHTML=`<div class="dr-hero">${g.cover?`<img src="${g.cover}" alt="${esc(g.name)}封面">`:''}<div><h2>${esc(g.name)}</h2><div class="dr-muted">${esc(g.en)}</div><p>${g.players}<br>${g.time}</p></div></div>`+tabs([['info','资料'],['inventory','馆藏'],['records','对局']],state.detail,'data-detail')+(state.detail==='info'?`<div class="dr-section"><div class="dr-row"><span>本体</span><span class="dr-tag">${g.available?'有可用馆藏':'待补充馆藏'}</span></div><p>${g.id===1?'在伯明翰发展产业与运输网络。':'共同改造火星，经营公司的发展计划。'}</p>${g.id===2?'<p>扩展：序曲 · 可在每局分别选择</p>':''}</div><div class="dr-section">${button('去活动提名','activity')}</div>`:state.detail==='inventory'?`<div class="dr-section"><strong>${g.owned?'小李的中文标准版':'尚未登记我的馆藏'}</strong><p class="dr-muted">${g.owned?'状态：'+(g.boxStatus||'可用')+' · 购入：'+(g.purchased||'2026-02-10'):'登记后可维护状态和购入时间'}</p>${button(g.owned?'编辑这盒':'登记我的馆藏',g.owned?'edit-box':'add-box')}</div>`:historyRows(state.game));bottom.hidden=false;bottom.innerHTML=button('我也有一盒','add-box')+primary('记录一局','new-play');
    } else if(state.page==='activity') {
      const selected=nominations.filter(n=>n.activity===1);
      screen.innerHTML=`<div class="dr-section"><span class="dr-tag">${state.started?'已开始':'报名中'}</span><h2>周末桌游局</h2><div class="dr-muted">9 月 13 日 · 14:00–19:00</div><p>开场前可以修改自己的提名。</p></div>`+titleRow('大家想玩',state.started?null:'pick-nomination','提名桌游')+selected.map(n=>`<div class="dr-section"><div class="dr-row"><strong>${esc(game(n.game).name)}</strong><span>${n.people.length} 人</span></div><p class="dr-muted">${n.people.map(id=>member(id).name).join('、')}</p><button type="button" class="dr-button dr-block" data-vote="${n.game}" ${state.started?'disabled':''}>${state.started?'提名已截止':n.people.includes(1)?'已提名 · 点此修改':'我也想玩'}</button></div>`).join('')+titleRow('游戏安排',state.organizer?'add-plan':null,'加一桌')+`<div class="dr-section"><div class="dr-row"><strong>1 号桌</strong><span class="dr-muted">小陈携带</span></div><p>${esc(game(state.game).name)}</p>${button(state.checked||state.organizer?'记录这桌的对局':'打卡后可记录','activity-play',state.checked||state.organizer?'':'disabled')}</div>`;
    } else if(state.page==='editor') {
      screen.innerHTML=`<div class="dr-section"><strong>${esc(game(form.game).name)}</strong><div class="dr-muted">${form.date} · ${activityName(form.activity)}</div>${form.game===2?`<label class="dr-check"><input type="checkbox" data-expansion ${form.expanded?'checked':''}>加入「序曲」扩展</label>`:''}</div><label class="dr-field"><span>比赛方式</span><select data-mode>${Object.entries(modes).map(([v,n])=>`<option value="${v}" ${form.mode===v?'selected':''}>${n}</option>`).join('')}</select></label>`+titleRow('实际玩家','players','选择用户')+playerEditor()+`<label class="dr-field"><span>整局是否完成</span><select data-end>${[['completed','已完成'],['unfinished','没开完'],['table_flip','掀桌结束']].map(([v,n])=>`<option value="${v}" ${form.end===v?'selected':''}>${n}</option>`).join('')}</select></label><div class="dr-alert" data-result-summary aria-live="polite">${summary(form)}</div>`;bottom.hidden=false;bottom.innerHTML=button('存为草稿','save-draft')+primary('保存对局','save-play');
    } else if(state.page==='plays') {
      screen.innerHTML=tabs([['all','全体'],['mine','我的']],state.scope,'data-scope')+filterBar()+titleRow('已记录的对局','new-play','记录一局')+historyRows();
    } else if(state.page==='playdetail') {
      const p=records.find(x=>x.id===state.selectedRecord);
      screen.innerHTML=`<div class="dr-section"><span class="dr-tag">${p.draft?'草稿':p.end==='completed'?'已完成':'未完成'}</span><h2>${esc(game(p.game).name)}</h2><div class="dr-muted">${p.date} · ${activityName(p.activity)} · ${modes[p.mode]}</div></div><div class="dr-section">${p.selected.map(id=>{const status=p.statuses[id];let score=status==='recorded'?`${esc(p.scores[id])} 分`:labels[status];if(p.mode==='unscored')score='已参局';else if(p.mode==='team'&&status!=='gave_up')score=`${p.teams[id]} 队 · ${p.teamStatuses[p.teams[id]]==='recorded'?p.teamScores[p.teams[id]]+' 分':labels[p.teamStatuses[p.teams[id]]]}`;else if(['cooperative','solo'].includes(p.mode)&&status!=='gave_up')score=p.sharedStatus==='recorded'?'共同 '+p.sharedScore+' 分':labels[p.sharedStatus];return `<div class="dr-line"><div class="dr-person"><span class="dr-avatar">${member(id).short}</span><span>${member(id).name}</span></div><div style="text-align:right"><span>${score}</span><div class="dr-muted">${p.draft?'草稿，不计统计':personalResult(p,id)}</div></div></div>`;}).join('')}</div><div class="dr-alert">${summary(p)}</div><p class="dr-muted">由小李记录 · 名单和成绩可更正</p>`;bottom.hidden=false;bottom.innerHTML=button('更正记录','edit-play')+primary('查看统计','stats');
    } else if(state.page==='stats')screen.innerHTML=renderStats();
    else if(state.page==='imports') {
      screen.innerHTML=`<div class="dr-alert">历史记录先暂存，公开展示和入榜后续再决定。</div>${titleRow('导入来源')}<div class="dr-section"><button type="button" class="dr-option" data-action="mapping"><span>BG Stats 文件</span><span>JSON / bgsplay ›</span></button><button type="button" class="dr-option" data-action="bgg"><span>BGG 账号</span><span>收藏与对局 ›</span></button></div>${titleRow('我的导入任务')}<div class="dr-section"><strong>示例 BG Stats 备份</strong><p class="dr-muted">2 款桌游 · 2 条对局</p><span class="dr-tag">${state.imported?'暂存成功':'待匹配玩家'}</span><p>${button('查看匹配','mapping')}</p></div>`;
    } else if(state.page==='mapping') {
      screen.innerHTML=`<div class="dr-alert">保留来源中的玩家名称，逐个匹配小程序用户。</div>${titleRow('玩家对应')}<div class="dr-section">${['Li','Chen','未匹配玩家'].map((n,i)=>`<label class="dr-field"><span>来源玩家 · ${n}</span><select data-map="${i}"><option value="">暂不匹配</option>${members.map(m=>`<option value="${m.id}" ${state.mappings[i]===String(m.id)?'selected':''}>${m.name}</option>`).join('')}</select></label>`).join('')}</div><p class="dr-muted">同名不会自动绑定账号。原始资料保留，之后可以再调整。</p>`;bottom.hidden=false;bottom.innerHTML=button('稍后处理','imports')+primary('保存匹配并暂存','confirm-import');
    }
  }
  function chooseStatus(id,unit) {
    const status=unit==='shared'?form.sharedStatus:unit==='team'?form.teamStatuses[id]:form.statuses[id];
    const name=unit==='shared'?'共同':unit==='team'?id+' 队':member(Number(id)).name;
    const options=unit==='player'&&['team','cooperative','solo'].includes(form.mode)?Object.entries(labels).filter(([v])=>v!=='recorded'):Object.entries(labels);
    sheet(name+'的成绩',options.map(([v,n])=>`<button type="button" class="dr-option" data-select-state="${v}" data-subject="${id}" data-unit="${unit}"><span>${n}</span><span>${v===status?'✓':''}</span></button>`).join(''));
  }
  function save(draft) {
    if(!form.selected.length)return error('至少选择一位实际玩家');
    if(form.mode==='solo'&&form.selected.length!==1)return error('单人模式只能选择一位玩家');
    if(form.mode==='team'&&new Set(form.selected.map(id=>form.teams[id])).size<2)return error('团队竞技至少需要两队');
    for(const id of form.selected)if(form.statuses[id]==='recorded'&&form.scores[id]==='')form.statuses[id]='unrecorded';
    for(const id of [1,2])if(form.teamStatuses[id]==='recorded'&&form.teamScores[id]==='')form.teamStatuses[id]='unrecorded';
    if(form.sharedStatus==='recorded'&&form.sharedScore==='')form.sharedStatus='unrecorded';
    if(form.mode==='solo'&&form.statuses[form.selected[0]]==='gave_up')form.sharedResult='failure';
    if(!draft&&form.resultMethod&&form.resultMethod!=='score'&&(!form.winnerIds.length||!form.resultReason.trim()))return error('请指定赢家并填写结果说明');
    const id=form.id||Math.max(...records.map(p=>p.id))+1, p=JSON.parse(JSON.stringify({...form,id,draft}));
    const i=records.findIndex(x=>x.id===id);if(i<0)records.push(p);else records[i]=p;
    state.selectedRecord=id;state.game=p.game;navigate('playdetail');
  }
  root.addEventListener('click',e=>{
    if(e.target.classList.contains('dr-mask'))return close();
    const t=e.target.closest('button');if(!t||t.disabled)return;
    if(t.dataset.page){state.gameFilter=null;return navigate(t.dataset.page);}
    if(t.dataset.game){state.game=Number(t.dataset.game);state.detail='info';return navigate('detail');}
    if(t.dataset.detail){state.detail=t.dataset.detail;return render();}
    if(t.dataset.scope){state.scope=t.dataset.scope;return render();}
    if(t.dataset.drill){state.gameFilter=Number(t.dataset.drill);return navigate('plays');}
    if(t.dataset.record){state.selectedRecord=Number(t.dataset.record);return navigate('playdetail');}
    if(t.dataset.scoreState)return chooseStatus(t.dataset.scoreState,t.dataset.unit);
    if(t.dataset.selectState){const {unit,subject,selectState}=t.dataset;if(unit==='shared'){form.sharedStatus=selectState;if(selectState!=='recorded')form.sharedScore='';if(selectState==='gave_up')form.sharedResult='failure';}else{(unit==='team'?form.teamStatuses:form.statuses)[subject]=selectState;if(selectState!=='recorded')(unit==='team'?form.teamScores:form.scores)[subject]='';}close();return render();}
    if(t.dataset.vote){const n=nominations.find(n=>n.game===Number(t.dataset.vote)&&n.activity===1);if(n.people.includes(1))return sheet('我的提名',button('保留提名','close')+` <button type="button" class="dr-button" data-withdraw="${n.game}">撤回提名</button>`);n.people.push(1);return render();}
    if(t.dataset.withdraw){nominations.find(n=>n.game===Number(t.dataset.withdraw)&&n.activity===1).people=nominations.find(n=>n.game===Number(t.dataset.withdraw)&&n.activity===1).people.filter(id=>id!==1);close();return render();}
    if(t.dataset.nominateGame){const id=Number(t.dataset.nominateGame);if(nominateAction==='plan')state.game=id;else{const n=nominations.find(n=>n.game===id&&n.activity===1);if(n&&!n.people.includes(1))n.people.push(1);else if(!n)nominations.push({game:id,activity:1,people:[1]});}close();return render();}
    const a=t.dataset.action;
    if(a==='back'){state.page=stack.pop()||'library';close();return render();}
    if(a==='import')return navigate('imports');
    if(['activity','stats','imports','mapping'].includes(a)){state.gameFilter=null;return navigate(a);}
    if(a==='close')return close();
    if(a==='my-inventory'){state.owned=true;return render();}
    if(a==='clear-game-filter'){state.gameFilter=null;return render();}
    if(a==='new-play'||a==='activity-play'){form={...fresh(),game:state.game,activity:a==='activity-play'?1:0};return navigate('editor');}
    if(a==='edit-play'){form=JSON.parse(JSON.stringify(records.find(p=>p.id===state.selectedRecord)));return navigate('editor');}
    if(a==='players'){draftSelection=form.selected.slice();return sheet('选择实际玩家',members.map(m=>`<label class="dr-check"><input type="checkbox" data-person-choice="${m.id}" ${draftSelection.includes(m.id)?'checked':''}><span class="dr-avatar">${m.short}</span><span>${m.name}</span></label>`).join(''),true,button('取消','close')+primary('确认','confirm-players'));}
    if(a==='confirm-players'){if(!draftSelection.length)return error('至少选择一位玩家');if(form.mode==='solo'&&draftSelection.length!==1)return error('单人模式只能选择一位玩家');form.selected=draftSelection;form.selected.forEach(id=>{form.statuses[id]??='unrecorded';form.scores[id]??='';});close();return render();}
    if(a==='save-play'||a==='save-draft')return save(a==='save-draft');
    if(a==='confirm-import'){state.imported=true;return navigate('imports');}
    if(a==='filter')return sheet('筛选桌游',`<label class="dr-check"><input type="checkbox" data-owned ${state.owned?'checked':''}>只看我的馆藏</label><label class="dr-check"><input type="checkbox" data-available ${state.available?'checked':''}>活动可用</label>`,true,button('取消','close')+primary('确认','confirm-filter'));
    if(a==='confirm-filter'){state.owned=overlay.querySelector('[data-owned]').checked;state.available=overlay.querySelector('[data-available]').checked;close();return render();}
    if(a==='activity-filter')return sheet('活动范围',activities.map(x=>`<label class="dr-check"><input type="checkbox" data-activity-choice="${x.id}" ${state.activityIds.includes(x.id)?'checked':''}>${x.name} · ${x.date.slice(5,7)} 月</label>`).join('')+'<p class="dr-muted">不勾选表示全部活动及独立记录。</p>',true,button('取消','close')+primary('确认','confirm-activities'));
    if(a==='confirm-activities'){state.activityIds=[...overlay.querySelectorAll('[data-activity-choice]:checked')].map(x=>Number(x.dataset.activityChoice));close();return render();}
    if(a==='confirm-dates'){const start=overlay.querySelector('[data-start]').value,end=overlay.querySelector('[data-finish]').value;if(!start||!end||start>end)return error('请选择有效的开始和结束日期');state.start=start;state.end=end;state.period='custom';close();return render();}
    if(['add-game','add-box','edit-box'].includes(a))return sheet(a==='add-game'?'录入桌游':a==='add-box'?'登记我的馆藏':'编辑馆藏',(a==='add-game'?'<label class="dr-field"><span>桌游名称</span><input data-new-name placeholder="输入中文或常用名称"></label>':`<p>${esc(game(state.game).name)}</p>`)+`<label class="dr-field"><span>归属</span><select><option>小李（我）</option></select></label><label class="dr-field"><span>库存状态</span><select data-box-status>${['待核实','可用','借出','停用'].map(n=>`<option ${a==='edit-box'&&n===(game(state.game).boxStatus||'可用')?'selected':''}>${n}</option>`).join('')}</select></label><label class="dr-field"><span>购入日期（可留空）</span><input type="date" data-purchased value="${a==='edit-box'?(game(state.game).purchased||'2026-02-10'):''}"></label>`,true,button('取消','close')+primary('保存','save-game'));
    if(a==='save-game'){const el=overlay.querySelector('[data-new-name]');if(el&&!el.value.trim())return error('请填写桌游名称');let g=game(state.game);if(el){g={id:games.length+1,name:el.value.trim(),en:'手动录入',players:'人数待补',time:'时长待补'};games.push(g);}g.owned=true;g.boxStatus=overlay.querySelector('[data-box-status]').value;g.available=g.boxStatus==='可用';g.purchased=overlay.querySelector('[data-purchased]').value;close();return render();}
    if(a==='pick-nomination'||a==='add-plan'){nominateAction=a==='add-plan'?'plan':'nominate';return sheet(a==='add-plan'?'安排游戏':'选择想玩的桌游',games.map(g=>`<button type="button" class="dr-option" data-nominate-game="${g.id}">${esc(g.name)}<span>›</span></button>`).join(''));}
    if(a==='insights'){const counts=new Map();filtered().filter(p=>!p.draft&&p.end==='completed').forEach(p=>counts.set(p.date.slice(0,7),(counts.get(p.date.slice(0,7))||0)+1));const max=Math.max(1,...counts.values());return sheet('游玩趋势',[...counts].sort().map(([m,n])=>`<div class="dr-row"><span>${m}</span><span>${n} 局</span></div><div class="dr-bar"><span style="width:${n/max*100}%"></span></div>`).join('')||'<p>这个范围内暂无已完成对局。</p>');}
    if(a==='bgg')return sheet('从 BGG 导入','<label class="dr-field"><span>BGG 用户名</span><input placeholder="输入用户名" aria-label="BGG 用户名"></label><label class="dr-check"><input type="checkbox" checked>拥有的桌游</label><label class="dr-check"><input type="checkbox" checked>对局历史</label>',true,button('取消','close')+primary('查看示例预览','mapping'));
  });
  root.addEventListener('input',e=>{
    if(e.target.matches('[data-search]')){state.search=e.target.value;screen.querySelector('[data-game-grid]').innerHTML=libraryGames().map(gameCard).join('')||'<div class="dr-empty">还没有找到这款桌游</div>';}
    if(e.target.matches('[data-score]')){const {unit,score}=e.target.dataset,value=e.target.value,status=value===''?'unrecorded':'recorded';if(unit==='shared'){form.sharedScore=value;form.sharedStatus=status;}else{(unit==='team'?form.teamScores:form.scores)[score]=value;(unit==='team'?form.teamStatuses:form.statuses)[score]=status;}screen.querySelector(`[data-score-state="${score}"][data-unit="${unit}"]`).textContent=labels[status]+' ▾';screen.querySelector('[data-result-summary]').textContent=summary(form);}
  });
  root.addEventListener('change',e=>{
    const t=e.target;
    if(t.matches('[data-person-choice]')){const id=Number(t.dataset.personChoice);draftSelection=t.checked?[...new Set([...draftSelection,id])]:draftSelection.filter(x=>x!==id);}
    if(t.matches('[data-mode]')){form.mode=t.value;form.resultMethod='score';form.winnerIds=[];if(['team','cooperative','solo','unscored'].includes(t.value))form.selected.forEach(id=>{if(form.statuses[id]==='recorded'){form.statuses[id]='unrecorded';form.scores[id]='';}});return render();}
    if(t.matches('[data-team]'))form.teams[t.dataset.team]=Number(t.value);
    if(t.matches('[data-shared-result]'))form.sharedResult=t.value;
    if(t.matches('[data-end]')){form.end=t.value;screen.querySelector('[data-result-summary]').textContent=summary(form);}
    if(t.matches('[data-expansion]'))form.expanded=t.checked;
    if(t.matches('[data-map]'))state.mappings[t.dataset.map]=t.value;
    if(t.matches('[data-stats-game]')){state.game=Number(t.value);render();}
    if(t.matches('[data-period]')){if(t.value==='custom')return sheet('自定义时间',`<label class="dr-field"><span>开始日期</span><input type="date" data-start value="${state.start}"></label><label class="dr-field"><span>结束日期</span><input type="date" data-finish value="${state.end}"></label>`,true,button('取消','cancel-dates')+primary('确认','confirm-dates'));state.period=t.value;render();}
  });
  root.addEventListener('click',e=>{if(e.target.closest('[data-action=cancel-dates]')){close();render();}});
  root.addEventListener('keydown',e=>{if(!overlay.hidden&&e.key==='Escape'){close();render();}if(!overlay.hidden&&e.key==='Tab'){const focusable=[...overlay.querySelectorAll('button,input,select')].filter(el=>!el.disabled),first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
  const extendedPages=new Set(['collection','cost','scorepaper','templates','timer','advanced','tags','offline','importreview']);
  const extra={rating:'8',wish:false,preordered:false,rounds:3,timerSeconds:0,timerStart:null,method:'total',sheet:[['资源','12','0',''],['建设','8','6',''],['奖励','5','2','']],tags:new Set(['适合聚会']),offlineResolved:false,publicHistory:false};
  const extraTitles={collection:'我的收藏',cost:'实物成本',scorepaper:'计分表',templates:'选择计分模板',timer:'对局计时',advanced:'详细统计',tags:'标签与筛选',offline:'待同步记录',importreview:'导入核对'};
  function arithmetic(text){if(!text.trim())return null;if(text.length>128||!/^[\d.\s+*/()\-]+$/.test(text))throw Error();const tokens=text.match(/\d*\.?\d+|[()+*/-]/g)||[];let i=0;function expr(depth){if(depth>16)throw Error();let v=term(depth+1);while(['+','-'].includes(tokens[i])){const op=tokens[i++],r=term(depth+1);v=op==='+'?v+r:v-r;}return v;}function term(d){let v=atom(d+1);while(['*','/'].includes(tokens[i])){const op=tokens[i++],r=atom(d+1);if(op==='/'&&r===0)throw Error();v=op==='*'?v*r:v/r;}return v;}function atom(d){if(d>20)throw Error();const t=tokens[i++];if(t==='('){const v=expr(d+1);if(tokens[i++]!==')')throw Error();return v;}if(t==='+'||t==='-')return(t==='-'?-1:1)*atom(d+1);if(!/^\d*\.?\d+$/.test(t||''))throw Error();return Number(t);}const n=expr(0);if(i!==tokens.length||!Number.isFinite(n))throw Error();return Math.round(n*1000)/1000;}
  function paperTotals(){const rows=extra.sheet.map(r=>r.slice(1).map(arithmetic));if(extra.method==='wins'&&rows.some(row=>row.some(v=>v===null)))return [null,null,null];return [0,1,2].map(c=>{const values=rows.map(r=>r[c]);return values.some(v=>v===null)?null:extra.method==='best'?Math.max(...values):extra.method==='wins'?values.filter((v,r)=>v===Math.max(...rows[r])).length:values.reduce((a,b)=>a+b,0);});}
  function clockText(){const s=extra.timerSeconds+(extra.timerStart?Math.floor((Date.now()-extra.timerStart)/1000):0);return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':');}
  const oldRender=render;
  render=function(){if(!extendedPages.has(state.page)){oldRender();if(state.page==='library')screen.insertAdjacentHTML('beforeend',`<div class="dr-h">${button('我的收藏与成本','collection')}${button('待同步','offline')}</div>`);if(state.page==='editor')screen.insertAdjacentHTML('beforeend',`<div class="dr-section"><label class="dr-field"><span>记录结果</span><select data-winner-method>${[["score","按分数判定"],["manual","只指定赢家"],["tiebreak","同分手动决胜"]].map(([v,n])=>`<option value="${v}" ${form.resultMethod===v?"selected":""}>${n}</option>`).join("")}</select>${form.resultMethod!=="score"?`<span class="dr-muted">${esc(form.resultReason)} ${button("修改赢家","choose-winners")}</span>`:""}</label><div class="dr-row">${button('计分表','scorepaper')}${button('计时与轮数','timer')}</div></div>`);if(state.page==='playdetail')screen.insertAdjacentHTML('beforeend',`<div class="dr-row">${button('查看计分表','scorepaper')}${button('我的标签','tags')}</div>`);if(state.page==='stats')screen.insertAdjacentHTML('beforeend',button('先手、连胜与分项统计','advanced'));if(state.page==='imports'){screen.querySelector('.dr-alert').textContent='历史先保存在私有任务中，逐条核对后才决定是否公开。';screen.insertAdjacentHTML('beforeend',button('核对差异与公开范围','importreview'));}return;}
    close();root.querySelector('[data-title]').textContent=extraTitles[state.page];root.querySelector('.dr-head [data-action=import]').hidden=true;bottom.hidden=true;bottom.innerHTML='';
    if(state.page==='collection')screen.innerHTML=`<div class="dr-section dr-collection"><span class="dr-number">66.7%</span><strong>馆藏游玩覆盖率</strong><div class="dr-muted">示例：已玩 4 / 拥有 6 款</div></div><div class="dr-grid"><div class="dr-section"><span class="dr-number">2</span>拥有未玩</div><div class="dr-section"><span class="dr-number">3</span>玩过未拥有</div></div>`+titleRow('我的游戏偏好')+`<div class="dr-section"><label class="dr-field"><span>我的评分（1–10）</span><input type="number" min="1" max="10" step=".1" value="${extra.rating}" data-rating></label><label class="dr-check"><input type="checkbox" data-wish ${extra.wish?'checked':''}>加入愿望单</label><label class="dr-check"><input type="checkbox" data-preorder ${extra.preordered?'checked':''}>已经预订</label></div><div class="dr-section">${button('查看实物成本','cost')} ${button('管理我的标签','tags')}</div>`;
    if(state.page==='cost')screen.innerHTML=`<div class="dr-section"><div class="dr-muted">本季度示例 · 人民币 CNY</div><span class="dr-number">¥ 360.00</span><div>整盒购入价</div><div class="dr-ruleline"></div><div class="dr-metrics"><div><span class="dr-number">30.00</span>每局</div><div><span class="dr-number">15.00</span>每小时</div><div><span class="dr-number">7.50</span>人均</div></div></div><div class="dr-section"><strong>工业革命：伯明翰 · 我的中文标准版</strong><p>明确使用本盒：12 局 · 24 小时 · 48 人次</p><span class="dr-tag">3 局时长缺失</span><p class="dr-muted">时长缺失的局不进入小时成本分母。</p></div><div class="dr-alert">多币种分别计算；未记录使用哪一盒的局不猜归属。</div>`;
    if(state.page==='scorepaper'){screen.innerHTML=titleRow('工业革命：伯明翰','templates','更换模板')+`<label class="dr-field"><span>计算方式</span><select data-paper-method><option value="total" ${extra.method==='total'?'selected':''}>累计总分</option><option value="best" ${extra.method==='best'?'selected':''}>最佳一轮</option><option value="wins" ${extra.method==='wins'?'selected':''}>赢得轮数</option></select></label><div class="dr-paper"><div class="dr-paper-row"><strong>计分项</strong><strong>小李</strong><strong>小陈</strong><strong>小赵</strong></div>${extra.sheet.map((row,r)=>`<div class="dr-paper-row"><span>${row[0]}</span>${row.slice(1).map((v,c)=>`<input aria-label="${row[0]} · ${members[c].name}" data-paper-row="${r}" data-paper-col="${c+1}" value="${v}" placeholder="未填">`).join('')}</div>`).join('')}<div class="dr-paper-row" data-paper-total><strong>总计</strong>${paperTotals().map(v=>`<strong>${v===null?'未齐':v}</strong>`).join('')}</div></div><div class="dr-alert">可输入 2+3、负数或括号算式。空白单独保留，不作 0 分。</div>${button('添加一行','add-paper-row')}<div class="dr-section"><label class="dr-check"><input type="checkbox" data-paper-zero>将小赵的分项填为0（保留个人状态）</label></div>`;bottom.hidden=false;bottom.innerHTML=button('返回记录','editor')+primary('计算并回填','save-paper');}
    if(state.page==='templates')screen.innerHTML=`<div class="dr-section"><strong>适用于当前游戏</strong><p class="dr-muted">按扩展、玩法和人数匹配，选用后保留版本快照。</p></div>`+['普通分项 · 通用','轮次计分 · 通用','伯明翰标准玩法 · v1'].map((n,i)=>`<button class="dr-option" type="button" data-template-choice="${i}"><span>${n}</span><span>选择 ›</span></button>`).join('');
    if(state.page==='timer'){screen.innerHTML=`<div class="dr-section dr-collection"><span class="dr-timer" data-timer-value>${clockText()}</span><p class="dr-muted">${extra.timerStart?'正在计时':'已暂停 / 尚未开始'}</p><div class="dr-row">${button(extra.timerStart?'暂停':'开始 / 继续',extra.timerStart?'timer-pause':'timer-start')}${button('结束计时','timer-stop')}</div></div><label class="dr-field"><span>实际轮数</span><input type="number" min="1" value="${extra.rounds}" data-rounds></label><div class="dr-alert">轮数独立记录；离开后重新打开可恢复计时状态。</div>`;}
    if(state.page==='advanced')screen.innerHTML=`<div class="dr-section"><strong>工业革命：伯明翰</strong><p class="dr-muted">全体本季度示例 · 标准玩法 · 个人竞赛 · 4 人</p><div class="dr-metrics"><div><span class="dr-number">3</span>最长连胜</div><div><span class="dr-number">1</span>当前连胜</div><div><span class="dr-number">2</span>同分决胜</div></div></div><div class="dr-section"><table><thead><tr><th>参与情况</th><th>获胜 / 样本</th><th>胜率</th></tr></thead><tbody><tr><td>先手</td><td>4 / 12</td><td>33.3%</td></tr><tr><td>第一次玩</td><td>2 / 8</td><td>25.0%</td></tr></tbody></table><p class="dr-muted">先手未填 3 局，新手标记未填 5 人次。</p></div>`+titleRow('按胜负比较分项')+`<div class="dr-section"><table><thead><tr><th>分项</th><th>胜者均分</th><th>未获胜均分</th></tr></thead><tbody><tr><td>资源</td><td>16.5</td><td>12.8</td></tr><tr><td>建设</td><td>24.2</td><td>19.6</td></tr></tbody></table><p class="dr-muted">只比较已审核的相同计分结构；每个分项分别标记缺失样本。</p></div>`;
    if(state.page==='tags')screen.innerHTML=titleRow('我的游戏标签')+`<div class="dr-section">${['适合聚会','想复盘','两个人就能开','规则已熟悉'].map(n=>`<label class="dr-check"><input type="checkbox" data-extra-tag="${n}" ${extra.tags.has(n)?'checked':''}>${n}</label>`).join('')}</div><div class="dr-section"><strong>已保存的组合筛选</strong><button type="button" class="dr-option" data-action="saved-filter"><span>我的馆藏 · 四人 · 120 分钟以内</span><span>查看 ›</span></button></div><div class="dr-alert">标签与偏好属于个人；活动“最想开”仍按活动提名统计。</div>`;
    if(state.page==='offline')screen.innerHTML=extra.offlineResolved?'<div class="dr-empty">已处理冲突，没有待同步记录</div>':`<div class="dr-section"><span class="dr-tag">需要核对</span><h2>更正一局成绩</h2><p>另一台设备也修改了这条记录。</p><div class="dr-compare"><div><span class="dr-muted">本机修改</span><strong>小陈 · 0 分</strong><span>第 3 轮补录</span></div><div><span class="dr-muted">服务器版本</span><strong>小陈 · 未填写</strong><span>仍未补齐</span></div></div><p class="dr-muted">核对后以新的版本提交，不会自动覆盖。</p>${primary('确认使用本机修改','resolve-offline')} ${button('保留服务器版本','resolve-offline')}</div>`;
    if(state.page==='importreview')screen.innerHTML=`<div class="dr-section"><span class="dr-tag">${extra.publicHistory?'已公开':'私有暂存'}</span><h2>工业革命：伯明翰</h2><div class="dr-muted">来源示例 · 2026-09-06</div></div><div class="dr-section"><strong>来源与本地差异</strong><div class="dr-compare"><div><span class="dr-muted">原记录</span><strong>60 分钟</strong><span>轮数未填</span></div><div><span class="dr-muted">新来源</span><strong>75 分钟</strong><span>3 轮</span></div></div>${button('逐个匹配玩家','mapping')}</div><div class="dr-section"><strong>相似对局</strong><p class="dr-muted">同游戏 · 同一天 · 三位相同玩家</p><label class="dr-check"><input type="radio" name="source-choice" checked>关联同一局，保留原有成绩</label><label class="dr-check"><input type="radio" name="source-choice">是另一局，另建私有记录</label></div>${button('核对公开范围','publish-review')}`;
  };
  root.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;const a=t.dataset.action;
    if(extendedPages.has(a)||a==='editor')return navigate(a);
    if(t.dataset.templateChoice!==undefined){extra.method='total';if(t.dataset.templateChoice==='1')extra.sheet=[['第 1 轮','','',''],['第 2 轮','','',''],['第 3 轮','','','']];return navigate('scorepaper');}
    if(a==='add-paper-row'){extra.sheet.push(['补记 '+extra.sheet.length,'','','']);return render();}
    if(a==='save-paper'){try{if(form.mode!=='individual'||form.selected.some(id=>id>3))return error('当前示例计分表对应这三位个人玩家；其他阵容请在小程序中建立对应的计分表');const totals=paperTotals();totals.forEach((v,i)=>{if(['gave_up','unfinished','table_flip'].includes(form.statuses[i+1]))return;form.scores[i+1]=v===null?'':String(v);form.statuses[i+1]=v===null?'unrecorded':'recorded';});return navigate('editor');}catch(e){return error('请检查算式，不支持的内容不会被执行。');}}
    if(a==='timer-start'){if(!extra.timerStart)extra.timerStart=Date.now();return render();}if(a==='timer-pause'||a==='timer-stop'){if(extra.timerStart)extra.timerSeconds+=Math.floor((Date.now()-extra.timerStart)/1000);extra.timerStart=null;return render();}
    if(a==='resolve-offline'){extra.offlineResolved=true;return render();}
    if(a==='saved-filter'){state.owned=true;return navigate('library');}
    if(a==='publish-review')return sheet('公开这一局历史','<p>公开玩家、成绩、地点与备注。只公开本次选中的一局。</p><label class="dr-check"><input type="checkbox" data-confirm-public>我已核对公开内容</label><label class="dr-check"><input type="checkbox" data-confirm-unmatched>允许显示尚未匹配的历史人物</label><label class="dr-field"><span>核对说明</span><input data-public-reason placeholder="说明已核对的内容"></label>',true,button('暂不公开','close')+primary('确认公开','publish-sample'));
    if(a==='publish-sample'){if(!overlay.querySelector('[data-confirm-public]').checked||!overlay.querySelector('[data-confirm-unmatched]').checked||!overlay.querySelector('[data-public-reason]').value.trim())return error('请确认公开内容、未匹配人物的展示，并填写说明');extra.publicHistory=true;close();return render();}
  });
  root.addEventListener('input',e=>{const t=e.target;if(t.dataset.paperRow!==undefined){extra.sheet[Number(t.dataset.paperRow)][Number(t.dataset.paperCol)]=t.value;try{screen.querySelector('[data-paper-total]').innerHTML='<strong>总计</strong>'+paperTotals().map(v=>`<strong>${v===null?'未齐':v}</strong>`).join('');}catch(e){screen.querySelector('[data-paper-total]').innerHTML='<strong>总计</strong><span>待检查算式</span>';}}if(t.matches('[data-rating]'))extra.rating=t.value;if(t.matches('[data-rounds]'))extra.rounds=Number(t.value);});
  root.addEventListener('change',e=>{const t=e.target;if(t.matches('[data-paper-method]')){extra.method=t.value;render();}if(t.matches('[data-paper-zero]')){extra.sheet.forEach(r=>r[3]=t.checked?'0':'');render();}if(t.matches('[data-wish]'))extra.wish=t.checked;if(t.matches('[data-preorder]'))extra.preordered=t.checked;if(t.dataset.extraTag){if(t.checked)extra.tags.add(t.dataset.extraTag);else extra.tags.delete(t.dataset.extraTag);}if(t.matches('[data-winner-method]')){if(!['individual','team'].includes(form.mode)){form.resultMethod='score';render();return error('合作和单人请使用共同挑战结果');}form.resultMethod=t.value;form.winnerIds=[];if(t.value!=='score')chooseWinners();else render();}});
  function chooseWinners(){const units=form.mode==='team'?[1,2].map(id=>({id,name:id+' 队',status:form.teamStatuses[id]})):members.filter(m=>form.selected.includes(m.id)).map(m=>({...m,status:form.statuses[m.id]}));sheet('指定赢家',units.map(m=>`<label class="dr-check"><input type="checkbox" data-winner="${m.id}" ${(form.winnerIds||[]).includes(m.id)?'checked':''} ${['gave_up','unfinished','table_flip'].includes(m.status)?'disabled':''}>${m.name}${m.status==='gave_up'?' · 摆烂不能获胜':''}</label>`).join('')+`<label class="dr-field"><span>决胜或更正说明</span><input data-winner-reason placeholder="说明采用的规则" value="${esc(form.resultReason)}"></label>`,true,button('取消','cancel-winners')+primary('确认选择','confirm-winners'));}
  root.addEventListener('click',e=>{const a=e.target.closest('button')?.dataset.action;if(a==='choose-winners')chooseWinners();if(a==='cancel-winners'){form.resultMethod='score';form.winnerIds=[];close();render();}if(a==='confirm-winners'){const ids=[...overlay.querySelectorAll('[data-winner]:checked')].map(t=>Number(t.dataset.winner)),reason=overlay.querySelector('[data-winner-reason]').value.trim();if(!ids.length||!reason)return error('请选择至少一位赢家并填写说明');if(form.resultMethod==='tiebreak'){const values=form.mode==='team'?form.teamScores:form.scores,units=form.mode==='team'?[1,2]:form.selected,known=units.filter(id=>values[id]!=='');if(known.length!==units.length)return error('同分决胜需先补齐可比较的分数');const best=Math.max(...known.map(id=>Number(values[id]))),tied=known.filter(id=>Number(values[id])===best);if(tied.length<2||ids.some(id=>!tied.includes(id)))return error('请从并列最高分中选择赢家');}form.winnerIds=ids;form.resultReason=reason;close();render();}});
  setInterval(()=>{const label=screen.querySelector('[data-timer-value]');if(label&&extra.timerStart)label.textContent=clockText();},1000);

  render();
  if(globalThis.Tweak){const tweak=new Tweak({container:root,onChange:render});tweak.addToggle(state,'recent',{label:'展示近期馆藏'});tweak.addToggle(state,'checked',{label:'当前用户已打卡'});tweak.addToggle(state,'organizer',{label:'当前用户为活动创建者'});tweak.addToggle(state,'started',{label:'活动已经开始'});}
})();
