const api=require('../../services/boardgames'),F=require('../../utils/boardgameFilters');
Page({...require('../../utils/boardgameMedia'),data:{id:null,name:'活动桌游',summary:null,loading:false,saving:false,error:'',tab:'nominations',gameOpen:false,games:[],search:'',formOpen:false,formKind:'nomination',form:{},selectedGame:null,expansions:[],boxes:[],boxIndex:0,peopleOpen:false,people:[],peopleCursor:null,peopleTitle:'提名的人'},
 onLoad(o={}){const id=Number(o.id||o.activity_id);this.setData({id:Number.isSafeInteger(id)&&id>0?id:null,activityOpen:false,activityItems:[],activityLoading:false,activityError:''});},onShow(){return this.load();},
 async load(){if(!this.data.id){this.setData({loading:false,summary:null});return;}this.setData({loading:true,error:''});try{const activity=await api.get(`/activities/${this.data.id}`),summary=await api.get(`/activities/${this.data.id}/boardgames`);this.setData({summary,name:activity.name||activity.title||'活动桌游',activityStatus:activity.status||'',activityUnavailable:['已取消','已流局','已删除'].includes(activity.status)});}catch(e){this.setData({summary:null,error:api.message(e)});}finally{this.setData({loading:false});}},
 async openActivities(){this.setData({activityOpen:true,activityLoading:true,activityError:''});try{const items=await api.get('/activities');this.setData({activityItems:items.filter(a=>a.status!=='已删除').map(a=>({id:a.id,name:a.name,status:a.status}))});}catch(e){this.setData({activityError:api.message(e)});}finally{this.setData({activityLoading:false});}},
 closeActivities(){this.setData({activityOpen:false});},chooseActivity(e){const id=Number(e.currentTarget.dataset.id);if(this.data.activityItems.some(a=>a.id===id))wx.redirectTo({url:'/pages/boardgame_activity/boardgame_activity'+api.query({id})});},
 tab(e){this.setData({tab:e.currentTarget.dataset.tab});},history(){wx.navigateTo({url:F.link('boardgame_history',{activity_ids:[this.data.id]})});},
 record(e){const summary=this.data.summary;if(!summary||!summary.permissions.can_record)return;const data=e.currentTarget.dataset;
  const nomination=data.kind==='nomination'?summary.nominations.find(n=>n.game.id===Number(data.id)):null;
  const plan=data.kind!=='nomination'&&data.id?summary.plans.find(p=>p.id===Number(data.id)):null;
  if(data.id&&!nomination&&!plan){this.setData({error:'这项安排已变化，请刷新后重新选择'});return;}
  wx.navigateTo({url:'/pages/boardgame_play/boardgame_play'+api.query({activity_id:this.data.id,game_id:nomination?nomination.game.id:plan&&plan.game_id,plan_id:plan&&plan.id,from_nomination:nomination?1:null,quick_start:nomination||plan?1:null})});},
 async add(e){this._key=api.uuid();this.setData({formKind:e.currentTarget.dataset.kind||'nomination',gameOpen:true,search:''});await this.searchGames();},closeGames(){this.setData({gameOpen:false});},searchInput(e){this.setData({search:e.detail.value});},
 async searchGames(){try{const r=await api.get('/boardgames',{q:this.data.search,limit:100});this.setData({games:r.items});}catch(e){this.setData({error:api.message(e)});}},
 async chooseGame(e){const game=this.data.games.find(g=>g.id===Number(e.currentTarget.dataset.id));if(!game)return;const mine=(this.data.summary.my_nominations||[]).find(n=>n.game_id===game.id)||(this.data.summary.nominations.find(n=>n.game.id===game.id)||{}).mine;
  const form=this.data.formKind==='nomination'?{...(mine||{expected_revision:0}),expected_revision:mine?mine.revision:0,expansions:mine?mine.expansions:[],note:mine?mine.note:null}:{game_id:game.id,inventory_id:null,bring_user_id:null,bring_label:null,table_label:null,note:null,sort_order:this.data.summary.plans.length,expansions:[]};
  this.setData({selectedGame:game,form,gameOpen:false,formOpen:true});await this.loadOptions();},
 async editNomination(e){const group=this.data.summary.nominations.find(g=>g.game.id===Number(e.currentTarget.dataset.id));this.setData({selectedGame:group.game,formKind:'nomination',form:{...group.mine,expected_revision:group.mine.revision},formOpen:true});await this.loadOptions();},
 async editPlan(e){const p=this.data.summary.plans.find(p=>p.id===Number(e.currentTarget.dataset.id));this.setData({selectedGame:p.game,formKind:'plan',form:{...p},formOpen:true});await this.loadOptions();},
 async loadOptions(){try{const [exp,box]=await Promise.all([api.get(`/boardgames/${this.data.selectedGame.id}/expansions`),api.get('/boardgame-inventory',{game_id:this.data.selectedGame.id,limit:100})]);const boxes=[{id:null,label:'暂未指定实物'},...box.items.map(b=>({...b,label:`${b.owner.display_name} · ${b.edition_label||b.edition_name||'默认版本'}`}))];const options=await Promise.all(exp.items.map(x=>api.get('/boardgame-inventory',{game_id:x.game.id,limit:100})));this.setData({boxes,boxIndex:Math.max(0,boxes.findIndex(b=>b.id===this.data.form.inventory_id)),expansions:exp.items.map((x,i)=>{const selected=this.data.form.expansions.find(e=>e.game_id===x.game.id);const optionsFor=[{id:null,label:'未指定实物'},...options[i].items.map(b=>({id:b.id,label:`${b.owner.display_name} · ${b.edition_label||b.edition_name||'默认版本'}`}))];return {...x,selected:!!selected,modules_note:selected&&selected.modules_note||'',compatibility_note:selected&&selected.compatibility_note||'',boxes:optionsFor,boxIndex:Math.max(0,optionsFor.findIndex(b=>b.id===(selected&&selected.inventory_id)))};})});}catch(e){this.setData({error:api.message(e)});}},
 closeForm(){if(!this.data.saving)this.setData({formOpen:false});},field(e){this._key=api.uuid();const key=e.currentTarget.dataset.key;this.setData({[`form.${key}`]:e.detail.value||null,...(key==='bring_label'?{'form.bring_user_id':null}:{})});},box(e){const i=Number(e.detail.value);this._key=api.uuid();this.setData({boxIndex:i,'form.inventory_id':this.data.boxes[i].id});},
 expansion(e){const id=Number(e.currentTarget.dataset.id),selected=e.detail.value;let rows=this.data.form.expansions.filter(x=>x.game_id!==id);if(selected)rows.push({game_id:id,modules_note:null,compatibility_note:null,inventory_id:null});this.setData({'form.expansions':rows,expansions:this.data.expansions.map(x=>({...x,selected:rows.some(e=>e.game_id===x.game.id)}))});this._key=api.uuid();},
 expansionNote(e){this.expansionValue(Number(e.currentTarget.dataset.id),e.currentTarget.dataset.key||'modules_note',e.detail.value||null);},expansionBox(e){const id=Number(e.currentTarget.dataset.id),exp=this.data.expansions.find(x=>x.game.id===id),i=Number(e.detail.value);this.expansionValue(id,'inventory_id',exp.boxes[i].id);this.setData({expansions:this.data.expansions.map(x=>x.game.id===id?{...x,boxIndex:i}:x)});},expansionValue(id,key,value){this._key=api.uuid();this.setData({'form.expansions':this.data.form.expansions.map(e=>e.game_id===id?{...e,[key]:value}:e),expansions:this.data.expansions.map(e=>e.game.id===id?{...e,[key]:value}:e)});},
 async save(){if(this.data.saving)return;this.setData({saving:true,error:''});try{const f=this.data.form,plan=this.data.formKind==='plan';let body=plan?{game_id:this.data.selectedGame.id,inventory_id:f.inventory_id||null,bring_user_id:f.bring_user_id||null,bring_label:f.bring_label||null,table_label:f.table_label||null,note:f.note||null,sort_order:f.sort_order||0,expansions:f.expansions.map(e=>({game_id:e.game_id,inventory_id:e.inventory_id||null,bring_user_id:e.bring_user_id||null,bring_label:e.bring_label||null,sort_order:e.sort_order||0,modules_note:e.modules_note||null,compatibility_note:e.compatibility_note||null}))}: {expected_revision:f.expected_revision,note:f.note||null,expansions:f.expansions.map(e=>({game_id:e.game_id,modules_note:e.modules_note,compatibility_note:e.compatibility_note||null}))};if(plan&&f.id)body.expected_revision=f.revision;
  await api.send(`/activities/${this.data.id}/`+(plan?`game-plans${f.id?'/'+f.id:''}`:`nominations/${this.data.selectedGame.id}/me`),plan?(f.id?'PATCH':'POST'):'PUT',body,this._key);this.setData({formOpen:false});await this.load();}catch(e){this.setData({error:api.message(e)});}finally{this.setData({saving:false});}},
 async withdraw(e){const group=this.data.summary.nominations.find(n=>n.game.id===Number(e.currentTarget.dataset.id));if(!group||!group.mine)return;try{await api.send(`/activities/${this.data.id}/nominations/${group.game.id}/me`+api.query({expected_revision:group.mine.revision}),'DELETE');await this.load();}catch(e){this.setData({error:api.message(e)});}},
 async removePlan(e){const p=this.data.summary.plans.find(p=>p.id===Number(e.currentTarget.dataset.id));try{await api.send(`/activities/${this.data.id}/game-plans/${p.id}`+api.query({expected_revision:p.revision}),'DELETE');await this.load();}catch(e){this.setData({error:api.message(e)});}},
 async move(e){const index=Number(e.currentTarget.dataset.index),rows=this.data.summary.plans.slice(),target=index+Number(e.currentTarget.dataset.step);if(target<0||target>=rows.length)return;[rows[index],rows[target]]=[rows[target],rows[index]];try{await api.send(`/activities/${this.data.id}/game-plan-order`,'PUT',{items:rows.map((p,i)=>({id:p.id,expected_revision:p.revision,sort_order:i}))});await this.load();}catch(e){this.setData({error:api.message(e)});}},
 async people(e){this._peopleGame=e.currentTarget.dataset.id;this.setData({peopleOpen:true,people:[],peopleCursor:null});await this.morePeople();},closePeople(){this.setData({peopleOpen:false});},async morePeople(){try{const r=await api.get(`/activities/${this.data.id}/nominations/${this._peopleGame}/people`,{limit:50,cursor:this.data.peopleCursor});this.setData({people:[...this.data.people,...r.items],peopleCursor:r.next_cursor});}catch(e){this.setData({error:api.message(e)});}}
});
